-- Bestiário Livro Base — Criaturas de Sangue (11) + O Diabo (chefe único de alto VD).

insert into creatures (source_id, name, vd, flavor_text, descritores, tamanho, presenca_dt, presenca_dano, presenca_nex_imune, percepcao, iniciativa, defesa, fortitude, reflexos, vontade, pv_maximo, pv_machucado, resistencias, vulnerabilidades, atributos, pericias, deslocamento, habilidades, acoes, enigma_medo, sort_order)
values
(
  (select id from sources where slug = 'ordem_paranormal'), 'Aberração de Carne', 40,
  'Originalmente, a aberração de carne foi um experimento fracassado para juntar dois corpos em um só. A dor agoniante das duas cobaias que se mantiveram conscientes durante todo o processo tormentoso se transformou numa fúria desoladora alimentada pelo Sangue. Os corpos tomaram uma aparência deformada, inchada e irreconhecível, com a pele completamente vermelha, seus olhos comidos, suas quatro pernas e quatro braços se movimentando com agressividade buscando agarrar tudo ao seu redor e uma enorme abertura se assemelhando a uma boca circular com incontáveis dentes se abrindo no ponto onde seus estômagos estavam costurados. Pode chegar a até dois metros e vinte de altura e é extremamente pesada.',
  '{Sangue}', 'Grande', 15, '3d6 mental', 30, '+5 (Percepção às Cegas)', '+0', 19, '+10', '+0', '+0', 70, 35, 'Balístico, impacto, perfuração 5; Sangue 10', 'Morte',
  '{"agi":1,"for":3,"int":0,"pre":1,"vig":3}', null, '9m | 6',
  '[]',
  '[{"tipo":"Padrão","nome":"Agredir (Pancada, corpo a corpo x2)","teste":"+10 (3d20)","dano":"2d6+6 impacto"},{"tipo":"Reação","nome":"Agarrão","teste":"+12 (3d20)","dano":null,"descricao":"Se acertar um ataque de pancada, tenta agarrar o alvo; mantém até 2 personagens agarrados por vez."},{"tipo":"Movimento","nome":"Abocanhar","teste":null,"dano":"3d6 perfuração/turno (Fortitude DT 15 reduz à metade)","descricao":"Leva até 2 agarrados pra dentro da boca central; qualquer personagem adjacente pode gastar ação padrão + Atletismo DT 20 pra tentar tirar alguém de dentro."}]',
  null, 1
),
(
  (select id from sources where slug = 'ordem_paranormal'), 'Aniquilação', 380,
  'A maior criatura já registrada na história da Realidade. Apenas relatos de civilizações distantes foram encontrados como evidência desse ser que só pode ser descrito como um apocalipse paranormal — "A Besta do Apocalipse", "O Dragão do Inferno". Uma aberração com mais de dez metros de altura, braços que contêm braços menores que brotam de todo seu comprimento, espinhos alongados, tentáculos entrelaçados, uma enorme bocarra com dentes do tamanho de pessoas adultas, e asas incapazes de erguer seu corpo colossal mas que produzem um som ensurdecedor ao se agitarem. Não há registro de alguém que tenha conseguido matá-la ou dissipá-la — pode estar apenas dormente, aguardando o despertar.',
  '{Sangue}', 'Colossal', 45, '9d8 mental', null, '+20 (4d20, Percepção às Cegas)', '+20 (4d20)', 58, '+30 (5d20)', '+25 (4d20)', '+20 (4d20)', 1200, 600, 'Dano 50', 'Morte',
  '{"agi":4,"for":5,"int":3,"pre":4,"vig":5}', 'Atletismo +20 (5d20)', '15m | 10',
  '[]',
  '[{"tipo":"Padrão","nome":"Agredir (Garras, corpo a corpo x2)","teste":"+40 (5d20)","dano":"4d10+30 Sangue"},{"tipo":"Padrão","nome":"Agredir (Tentáculos Espinhentos, corpo a corpo x2)","teste":"+40 (5d20)","dano":"2d12+30 Sangue"},{"tipo":"Padrão","nome":"Agredir (Disparo de Espinhos, distância x3, médio)","teste":"+40 (4d20)","dano":"2d10+20 Sangue"},{"tipo":"Reação","nome":"Agarrão","teste":"+50 (5d20)","dano":null,"descricao":"Ao acertar tentáculos espinhentos, tenta agarrar; até 4 agarrados por vez."},{"tipo":"Reação","nome":"Instinto Aniquilador","descricao":"Qualquer um em alcance curto que se mova mais de 3m sofre um ataque de tentáculos espinhentos."},{"tipo":"Livre","nome":"Apertar e Destruir","dano":"40 Sangue","descricao":"No início do turno, aperta os agarrados."},{"tipo":"Movimento","nome":"Bater as Asas","dano":"8d6 Mental (Fortitude DT 40 reduz à metade e evita)","descricao":"Todos em alcance longo são empurrados 6m e ficam atordoados 1 rodada."},{"tipo":"Movimento","nome":"Estrangulamento Final","descricao":"Desloca 15m; quem fica adjacente durante o deslocamento fica agarrado e asfixiado (Reflexos DT 30 evita); escapar exige ação padrão + Reflexos DT 30."},{"tipo":"Completa","nome":"Tempestade de Espinhos","dano":"20d6+20 Sangue (Reflexos DT 40 reduz à metade)","descricao":"Todos em alcance médio; 1x/cena, e perde Disparo de Espinhos pelo resto da cena ao usar."}]',
  'Desconhecido. Ao resolver, perde a Resistência a Dano e a habilidade Tempestade de Espinhos.', 2
),
(
  (select id from sources where slug = 'ordem_paranormal'), 'Carente', 300,
  'Criatura mais famosa do escritor de terror Daniel Hartmann — manifestação nascida da inveja de um ser que nunca sentiu amor, e por isso busca devorar órgãos de pessoas que já foram mães, tentando consumir o amor que nunca recebeu. Originalmente toma a forma de uma pequena criança com lacerações no rosto vazio, batendo em portas e imitando o som de uma criança perdida chamando pela mãe — mas não consegue abrir portas sozinho. Quando alguém comete o erro de atender e abrir a porta, rasteja de dentro do rosto infantil uma criatura grotesca de mais de três metros, pele gosmenta, garras curvadas, um grande ferrão saindo de um rosto demoníaco, com o corpo da criança pendurado no topo como isca, conectado a um tentáculo com garras. Depois que a entrada é permitida uma vez, nada mais o impede de devorar aquilo de que carece.',
  '{Sangue,Morte}', 'Grande', 35, '7d8 mental', 90, '+10 (3d20, Percepção às Cegas)', '+15 (4d20)', 40, '+25 (4d20)', '+25 (4d20)', '+15 (3d20)', 700, 350, 'Balístico, impacto, perfuração e Sangue 20', 'Morte',
  '{"agi":4,"for":4,"int":2,"pre":3,"vig":4}', 'Atletismo +20 (4d20), Enganação +15 (3d20)', '12m | 8',
  '[{"nome":"Regeneração de Sangue","descricao":"Cura Acelerada 20; se ficar inconsciente ou sofrer dano de Energia, para de funcionar até o fim da cena."},{"nome":"Carência","descricao":"Qualquer ser que já esteve envolvido na gestação de outro ser recebe +1d20 em ataques contra o carente, mas o carente também recebe +1d20 contra esse ser."}]',
  '[{"tipo":"Padrão","nome":"Agredir (Garras de Sangue, corpo a corpo x2)","teste":"+35 (4d20)","dano":"2d8+20 Sangue"},{"tipo":"Padrão","nome":"Agredir (Ferrão de Sangue, corpo a corpo)","teste":"+35 (4d20)","dano":"2d12+20 Sangue"},{"tipo":"Padrão","nome":"Agredir (Tentáculo, corpo a corpo)","teste":"+35 (4d20)","dano":"2d8+20 Sangue"},{"tipo":"Movimento","nome":"Forma Infantil","descricao":"Contorce de volta pro corpo de criança pra passar em espaços pequenos; não pode abrir a primeira porta pra entrar num lugar, mas uma vez aberta, ignora essa restrição."},{"tipo":"Reação","nome":"Rasteira de Tentáculo","descricao":"1x/rodada, ao ficar adjacente a 2+ seres, ataca um com tentáculo; se acertar, alvo cai e é empurrado 6m."},{"tipo":"Livre","nome":"Sugada Mortal","descricao":"Com o ferrão, sugar fluidos apodrece órgãos; atingido fica debilitado e enjoado até o fim da cena (Fortitude DT 35 evita)."},{"tipo":"Movimento","nome":"Você é Minha Mamãe?","descricao":"Usa a forma infantil pra abraçar um adjacente, que fica paralisado até ser solto (Reflexos DT 25 evita); mantém indefinidamente, mas solta se sofrer dano de Energia."}]',
  null, 3
),
(
  (select id from sources where slug = 'ordem_paranormal'), 'Enpap-X', 180,
  'Originada de uma lenda perdida da antiga Suméria, surgiu da dor e tortura de um prisioneiro de guerra obrigado a marcar em sua pele os feitos terríveis cometidos por seu soberano. Odio, dor e angústia transformam a mente da pessoa numa tormenta enfurecida; as marcas em seu corpo preenchem o vazio da mente consumida com um nome lembrado pelo Conhecimento: enpap-X. Inicialmente controlado e acorrentado; se libertado das correntes e ferido, se transforma numa monstruosidade de quatro braços movida por vingança.',
  '{Sangue,Conhecimento}', 'Grande', 25, '6d6 mental', 60, '+10 (2d20, Percepção às Cegas)', '+10 (2d20)', 36, '+15 (3d20)', '+15 (2d20)', '+10 (2d20)', 360, 180, 'Balístico, impacto e perfuração 10, Sangue 20', 'Morte',
  '{"agi":2,"for":4,"int":1,"pre":2,"vig":3}', null, '12m | 8',
  '[{"nome":"Transformação","descricao":"Começa o combate como um \"existido\" comum (ficha à parte). Ao ser reduzido a 0 PV, em vez de morrer, se transforma: passa a usar esta ficha (inclusive nova Presença Perturbadora) e recupera todos os PV (360)."}]',
  '[{"tipo":"Padrão","nome":"Agredir (Socão, corpo a corpo x4)","teste":"+20 (4d20)","dano":"2d10+10 impacto"},{"tipo":"Padrão","nome":"Agredir (Correntes, distância x3, curto)","teste":"+15 (2d20)","dano":"2d8+10 impacto"},{"tipo":"Livre","nome":"Acorrentar","teste":"+17 (2d20)","descricao":"Ao acertar correntes num alvo Médio ou menor, tenta agarrar à distância; estrangula agarrados no início do turno por 4d6 dano de impacto; até 2 agarrados por vez."},{"tipo":"Reação","nome":"Forma Desencadeada","descricao":"Crítico com socão ou corrente pode derrubar o alvo ou empurrá-lo 3m."},{"tipo":"Reação","nome":"Crescer","descricao":"A cada socão que acerta, +1d6 cumulativo de dano nas próximas rolagens até o fim do turno."},{"tipo":"Movimento","nome":"Marcas do Terror","dano":"4d6 mental (Vontade DT 25 reduz à metade)","descricao":"Todos em alcance curto; quem passa fica imune até o fim da cena."}]',
  null, 4
),
(
  (select id from sources where slug = 'ordem_paranormal'), 'Kerberos', 340,
  'O cão de três cabeças, o demônio do poço, o guardião do portão do inferno. Besta enorme com mais de três metros de altura e sete de comprimento, seis patas, uma cauda, espinhos, veias saltadas pela pele vermelha carnosa, e três cabeças diferentes entre si. Só pode se manifestar num "Inferno" — área paranormal tomada pelo Sangue com a Membrana devastada por brutalidades impensáveis — como guardião de uma entrada importante. É ilógico e não toma decisões estratégicas, apenas protege um ponto específico.',
  '{Sangue}', 'Enorme', 35, '10d6 mental', 99, '+20 (3d20, Percepção às Cegas)', '+15 (4d20)', 46, '+25 (5d20)', '+20 (4d20)', '+15 (3d20)', 1150, 575, 'Balístico, impacto, perfuração e Sangue 20', 'Morte',
  '{"agi":4,"for":5,"int":0,"pre":3,"vig":5}', 'Atletismo +25 (5d20)', '18m | 12',
  '[{"nome":"Ataque Flexível","descricao":"Até 4 ataques por rodada, combinando corpo a corpo e à distância, nunca repetindo o mesmo ataque mais de 3x na mesma rodada."}]',
  '[{"tipo":"Padrão","nome":"Agredir (Mordida, corpo a corpo)","teste":"+40 (5d20)","dano":"4d12+30 Sangue"},{"tipo":"Padrão","nome":"Agredir (Disparo de Espinhos, distância, médio)","teste":"+35 (4d20)","dano":"4d8+20 Sangue"},{"tipo":"Livre","nome":"Devorar","descricao":"1x/cena, ao reduzir alguém a 0 PV com a mordida, devora e mata instantaneamente, recuperando metade dos PV totais da vítima (Fortitude DT 40 evita)."},{"tipo":"Completa","nome":"Derrubar e Devorar","teste":"+45 (5d20)","descricao":"Manobra de derrubar em alvo a até 3m; vencendo, desfere 3 mordidas (dano sobe pra 4d12+40)."}]',
  null, 5
),
(
  (select id from sources where slug = 'ordem_paranormal'), 'Minotauro', 280,
  'Forma de um animal enorme, furioso e bípede com mais de três metros, infectado com pústulas de Sangue e veias pulsantes por um lado do corpo — origem nas lendas gregas do monstro dos labirintos. No braço esquerdo, um machado de lâmina dupla fundido aos ossos e à carne. Uma das primeiras criaturas com registro de ter sido mantida em cativeiro pra estudo por investigadores paranormais há milênios; não se sabe por quê.',
  '{Sangue}', 'Grande', 35, '8d6 mental', 80, '+20 (3d20, Percepção às Cegas)', '+15 (4d20)', 44, '+20 (5d20)', '+15 (4d20)', '+10 (3d20)', 750, 375, 'Balístico, impacto, perfuração e Sangue 20', 'Morte',
  '{"agi":4,"for":5,"int":1,"pre":3,"vig":5}', 'Atletismo +20 (5d20)', '12m | 8',
  '[]',
  '[{"tipo":"Padrão","nome":"Agredir (Chifres, corpo a corpo)","teste":"+30 (5d20)","dano":"6d12+20 perfuração"},{"tipo":"Padrão","nome":"Agredir (Machado, corpo a corpo x2)","teste":"+32 (5d20)","dano":"4d12+20 corte"},{"tipo":"Livre","nome":"Cravar Chifres","descricao":"Investida com chifres que acerta crava e agarra o alvo (não pode atacar com chifres enquanto mantém); no fim de cada turno da vítima ainda agarrada, sofre 4d12+20 dano de Sangue."}]',
  null, 6
),
(
  (select id from sources where slug = 'ordem_paranormal'), 'Mulher Afogada', 140,
  'Lenda urbana popularizada entre crianças por pais evitando desperdício de água, que ganhou proporções terríveis após um escritor adaptá-la num conto de terror. Invocação sempre associada a mulheres que morreram afogadas de forma brutal e trágica. Se move em forma de Sangue líquido pelo encanamento de casas assombradas, identificável pela coloração avermelhada escorrendo das saídas de água; puxa alvos pra dentro do encanamento, afogando-os e devorando-os aos poucos. Criatura de Medo — exige processo complexo pra derrotar.',
  '{Sangue,Energia}', 'Grande', 25, '4d8 mental', 50, '+5 (2d20, Percepção às Cegas)', '+10 (4d20)', 28, '+10 (3d20)', '+10 (4d20)', '+5 (2d20)', 240, 120, 'Balístico, Energia, impacto e perfuração 10, Sangue 20', 'Morte',
  '{"agi":4,"for":3,"int":2,"pre":2,"vig":3}', null, '9m | 6 (forma líquida: 36m | 24)',
  '[{"nome":"Forma de Sangue","descricao":"Por padrão é encontrada como líquido de Sangue — nessa forma tem resistência a balístico/corte/impacto/perfuração/Sangue 20, desloca 36m e percorre canos/frestas/orifícios como líquido, e ganha as ações Afogar em Sangue, Arrancar Sangue e Invadir Órgãos; perde essas 3 ações ao ser invocada em forma física (após o Enigma de Medo ser desvendado)."}]',
  '[{"tipo":"Padrão","nome":"Agredir (Mordida, corpo a corpo)","teste":"+15 (3d20)","dano":"4d8+8 perfuração"},{"tipo":"Padrão","nome":"Agredir (Garras, corpo a corpo x2)","teste":"+15 (3d20)","dano":"4d6+6 corte"},{"tipo":"Padrão","nome":"Agredir (Jato de Sangue, distância, curto)","teste":"+10 (4d20)","dano":"4d8+8 Sangue"},{"tipo":"Movimento","nome":"Sugar Sangue","descricao":"Devora o corpo de um adjacente morto na cena, recupera 40 PV."},{"tipo":"Padrão (forma de Sangue)","nome":"Afogar em Sangue","descricao":"Invade nariz/boca de um alvo em alcance curto, afogando-o em Sangue; fica asfixiado; no início de cada turno, Fortitude DT 24 encerra a condição e expele a mulher afogada líquida pra um espaço adjacente."},{"tipo":"Reação (forma de Sangue)","nome":"Arrancar Sangue","dano":"6d6 Sangue + fraco","descricao":"Ao ser arrancada de um corpo que está afogando, carrega parte do sangue."},{"tipo":"Movimento (forma de Sangue)","nome":"Invadir Órgãos","dano":"6d6 Sangue + enjoado","descricao":"Invade órgãos vitais de quem está afogando."}]',
  'Ao assombrar um local, toda fonte de água vira "ponto de invocação"; aproximar-se pode manifestá-la fisicamente. Enfrentar diretamente é inútil (se move livremente por dentro do encanamento e se recupera). Derrotar: bloquear todas as saídas de água + fechar o registro hidráulico + abrir todas as torneiras, forçando a manifestação física sem lugar pra fugir.', 7
),
(
  (select id from sources where slug = 'ordem_paranormal'), 'Titã de Sangue', 220,
  'A maior versão já encontrada de um zumbi de Sangue — criatura monstruosa com mais de quatro metros de altura, massa de carne e Sangue endurecida e musculosa, veias saltadas por todo o corpo, e uma enorme boca com quatro quelíceras gigantes. Manifestado apenas em locais com a Membrana debilitada por massacres/carnificinas terríveis; pode se formar do aglomerado de vários corpos num só, ou de uma pessoa de exposição paranormal extremamente elevada sendo devorada pelo Sangue.',
  '{Sangue}', 'Enorme', 30, '7d6 mental', 70, '+15 (1d20, Percepção às Cegas)', '+10 (2d20)', 35, '+15 (4d20)', '+10 (2d20)', '+10 (1d20)', 550, 275, 'Balístico, impacto, perfuração e Sangue 20', 'Morte',
  '{"agi":2,"for":5,"int":1,"pre":1,"vig":4}', null, '12m | 8',
  '[{"nome":"Sede de Sangue","descricao":"Ataques causam +4d6 dano de Sangue em alvos machucados ou sangrando."}]',
  '[{"tipo":"Padrão","nome":"Agredir (Mordida, corpo a corpo)","teste":"+25 (5d20)","dano":"4d12+10 perfuração"},{"tipo":"Padrão","nome":"Agredir (Garras, corpo a corpo x2)","teste":"+25 (5d20)","dano":"4d8+10 corte"},{"tipo":"Livre","nome":"Estraçalhar","descricao":"Ao acertar mordida, causa 4d12+10 dano de perfuração + sangrando até o fim da cena (Reflexos DT 30 reduz o dano à metade e evita a condição)."}]',
  null, 8
),
(
  (select id from sources where slug = 'ordem_paranormal'), 'Zumbi de Sangue', 20,
  'Quando cadáveres mortos de forma brutal ou dolorosa são abandonados, servem de passagem pra entidade de Sangue devorá-los e tomar controle da forma física. A pele vira material gosmento e vermelho, ossos se desfazem virando carne pura, olhos se destroem, dentes crescem pontudos, unhas viram garras. O tempo de transformação é irregular; enfrentar um cadáver em transformação resulta num zumbi mais frágil. Cegos, detectam presenças pela movimentação da corrente de ar. Bestiais e agressivos, sem raciocínio estratégico.',
  '{Sangue}', 'Médio', 15, '2d6 mental', 25, '+10 (1d20, Percepção às Cegas)', '+5 (2d20)', 17, '+5 (2d20)', '+5 (2d20)', '+5 (1d20)', 45, 22, 'Balístico, impacto e perfuração 5, Sangue 10', 'Morte',
  '{"agi":2,"for":2,"int":0,"pre":1,"vig":2}', null, '9m | 6',
  '[]',
  '[{"tipo":"Padrão","nome":"Agredir (Garras, corpo a corpo x2)","teste":"+5 (2d20)","dano":"1d6+5 corte"}]',
  null, 9
),
(
  (select id from sources where slug = 'ordem_paranormal'), 'Zumbi de Sangue Bestial', 100,
  'Versão maior, mais forte e brutal — resultado de um cadáver torturado brutalmente com dores indescritíveis antes de morrer, ou de alguém com exposição paranormal elevada devorado por completo. É pesado, com massa até o triplo do cadáver original; corpo adaptado a forma quadrúpede animalesca; o crânio original é partido ao meio, virando uma enorme bocarra capaz de decapitar um humano numa mordida. Diferente da versão comum, é estratégico — se esconde e espera pra pegar alvos desprevenidos.',
  '{Sangue}', 'Grande', 20, '4d6 mental', 45, '+10 (2d20, Percepção às Cegas)', '+15 (2d20)', 23, '+10 (3d20)', '+5 (2d20)', '+5 (2d20)', 200, 100, 'Balístico, impacto e perfuração 5, Sangue 10', 'Morte',
  '{"agi":2,"for":3,"int":0,"pre":2,"vig":3}', 'Furtividade +13 (2d20)', '12m | 8',
  '[{"nome":"Furtivo e Letal","descricao":"Ao atacar alvo desprevenido, +1d20 nos testes de ataque e, se acertar, +2 dados de dano adicional do mesmo tipo por ataque."},{"nome":"Instinto Predatório","descricao":"Não sofre penalidade em Furtividade ao se mover o deslocamento normal."}]',
  '[{"tipo":"Padrão","nome":"Agredir (Mordida de Sangue, corpo a corpo)","teste":"+15 (3d20)","dano":"2d10+5 perfuração"},{"tipo":"Padrão","nome":"Agredir (Garras de Sangue, corpo a corpo x2)","teste":"+15 (3d20)","dano":"2d6+5 corte"}]',
  null, 10
),
(
  (select id from sources where slug = 'ordem_paranormal'), 'O Diabo', 400,
  'Conhecido por inúmeros nomes — o Príncipe do Ódio, o Imperador das Aberrações, o Portador do Trono, o Sangue Encarnado. Uma das manifestações do Outro Lado mais significativas da história: nunca foi derrotado, controlado ou aprisionado, e é capaz de invocar e controlar qualquer criatura paranormal irracional de Sangue na Realidade. Pele vermelha, chifruda, sorriso impetuoso e olhar macabro, presente em incontáveis culturas e lendas. Não age com sutileza. Sua presença está associada a estados mentais transtornados; se alimenta de sentimentos extremos e descontrolados. A maioria dos casos remonta a um Pacto. Regra inegável: você não deve se envolver com o Diabo. (Chefe único.)',
  '{Sangue,Conhecimento}', 'Médio', 45, '10d8 mental (pode escolher não ativar — ver Ardiloso)', null, '+25 (6d20, Percepção às Cegas)', '+35 (6d20)', 66, '+35 (6d20)', '+35 (6d20)', '+35 (6d20)', 1666, 833, 'Balístico, impacto e perfuração 20', 'Morte',
  '{"agi":6,"for":6,"int":6,"pre":6,"vig":6}', null, '18m | 12',
  '[{"nome":"Imunidades","descricao":"Atordoado, condições de paralisia, dano, e efeitos de Sangue."},{"nome":"Ardiloso","descricao":"Pode escolher não ativar sua Presença Perturbadora (costuma aparecer pra pessoas comuns pra fazer pactos)."},{"nome":"Potência de Sangue","descricao":"Recupera 50 PV no início de cada turno; modificador +35 em perícias baseadas em Força/Vigor/Presença, +25 nas demais."}]',
  '[{"tipo":"Padrão","nome":"Agredir (Arma Sangrenta, corpo a corpo x2)","teste":"+45 (6d20), crítico x3","dano":"2d10+50 Sangue"},{"tipo":"Padrão","nome":"Agredir (Chifre do Diabo, corpo a corpo)","teste":"+45 (6d20), crítico x3","dano":"2d8+50 Sangue"},{"tipo":"Padrão","nome":"Agredir (Arma Sangrenta, distância x2, médio)","teste":"+45 (6d20), crítico x3","dano":"2d10+50 Sangue"},{"tipo":"Livre","nome":"Explodir em Sangue","dano":"10d6 Sangue","descricao":"Ao causar dano com arma sangrenta ou tocar diretamente numa ferida; até 2x/turno."},{"tipo":"Livre","nome":"Sangrar","descricao":"Ao acertar com o chifre, pode soltá-lo preso no alvo (vulnerabilidade a Sangue até remover — ação padrão + 8d8 dano de Sangue pra remover); o chifre sempre recresce no início do turno do Diabo."},{"tipo":"Movimento","nome":"Transportar pelo Sangue","descricao":"Move-se através de sangue exposto (inclusive saindo de um personagem), até qualquer espaço com sangue exposto ou adjacente a um machucado/morrendo."},{"tipo":"Padrão","nome":"Senhor do Sangue","descricao":"1x/cena, invoca e controla criaturas de Sangue com VD somado até 400; aparecem em alcance médio e agem a partir da próxima rodada."},{"tipo":"Padrão","nome":"Pacto","dano":"10d6 mental","descricao":"Oferece um pacto de Sangue; se aceito, cumpre o prometido (com resoluções distorcidas); se o alvo enlouquecer, vira servo obcecado pelo Diabo pra sempre."},{"tipo":"Completa","nome":"Desejos de Sangue","descricao":"Todos em alcance médio entram em fúria e atacam outro personagem em alcance curto à escolha do Diabo (Vontade DT 45 evita); afetados usam a ação de maior potencial de dano, sem conjurar rituais; quem passa fica imune até o fim da cena."}]',
  'Ninguém sabe como derrotá-lo — registros falam de símbolos sagrados que não funcionam de verdade. Sabe-se que Morte é a entidade opressora do Sangue; talvez a resposta esteja no Lodo, não no Sangue. Ao resolver, perde imunidade a dano e os bônus de resistência caem pra +25.', 11
);
