-- Bestiário Livro Base — Criaturas de Morte (11) + O Deus da Morte (chefe único/Relíquia).

insert into creatures (source_id, name, vd, flavor_text, descritores, tamanho, presenca_dt, presenca_dano, presenca_nex_imune, percepcao, iniciativa, defesa, fortitude, reflexos, vontade, pv_maximo, pv_machucado, resistencias, vulnerabilidades, atributos, pericias, deslocamento, habilidades, acoes, enigma_medo, sort_order)
values
(
  (select id from sources where slug = 'ordem_paranormal'), 'Aracnasita', 80,
  'A distorção da exposição paranormal pode fazer um pequeno aracnídeo se deformar numa entidade parasitária enorme que se alimenta do tempo de vida humano pra se desenvolver — também chamada aranha preta da Morte. Originada de uma criatura da Realidade exposta a um símbolo de invocação de Morte. Ainda minúscula, surpreende vítimas se agarrando ao rosto pra mantê-las desacordadas, depois absorve o corpo inteiro ainda vivo num casulo no abdômen — quanto mais tempo absorve, maior e mais poderosa fica, podendo se reproduzir gerando pequenas cópias de si.',
  '{Morte}', 'Grande', 20, '4d6 mental', 40, '+10 (1◯, Percepção às Cegas)', '+10 (3◯)', 23, '+5 (2◯)', '+10 (3◯)', '+5 (1◯)', 140, 70, null, 'Energia',
  '{"agi":3,"for":2,"int":1,"pre":1,"vig":2}', 'Furtividade +8 (3◯)', '12m | 8',
  '[{"nome":"Imunidades","descricao":"Dano (exceto fogo)."},{"nome":"Percepção Tátil","descricao":"Percebe tudo em contato com sua teia, ignorando penalidades de visão/sentidos pra objetos/seres em contato com ela."}]',
  '[{"tipo":"Padrão","nome":"Agredir (Mordida, corpo a corpo)","teste":"+15 (2◯)","dano":"2d10+10 perfuração"},{"tipo":"Livre","nome":"Estacar","dano":"+1d10 Morte + agarrado","descricao":"Ao causar dano com a mordida, usa Lodo pra prender o alvo (solta com ação padrão + Atletismo DT 20, ou ajuda de adjacente)."},{"tipo":"Reação","nome":"Desovar Aranhas","descricao":"1x/cena, ao ficar machucada, desova aranhas menores; T1: 2d6 dano mental em alcance curto (Vontade DT 15 reduz à metade); T2+: também 2d8 dano de Morte (Fortitude DT 15 reduz à metade); T3+: alcance médio; T4+: quem morre em alcance médio vira nova aracnasita com 70 PV."},{"tipo":"Movimento","nome":"Disparar Teia","dano":"2d8+10 Morte/turno","descricao":"Teia em área de 3m em alcance curto; quem está ou entra fica agarrado (Reflexos DT 20 evita); escapa causando 15 de dano de corte na teia ou ação padrão + Atletismo DT 20; dura até o fim da cena."}]',
  'Se forma quando uma aranha entra em contato com o Lodo através de um símbolo poderoso — guarda uma grande quantidade de Lodo pelo corpo, quase impossível de ferir. O Lodo foge de fontes de calor; se sofrer dano de fogo, perde a imunidade a dano até o início do próximo turno.', 12
),
(
  (select id from sources where slug = 'ordem_paranormal'), 'Carniçal Preto da Morte', 200,
  'Originada de uma tentativa fracassada de dar consciência à entidade da Morte na Realidade — formada de Lodo entrelaçado a partir de um crânio humano apodrecido. Os sigilos de Conhecimento usados pra invocá-lo fazem o Lodo tentar replicar a estrutura humana, resultando numa forma resistente, magra, com anatomia muscular exposta. Postura inteligente, caminha com arrogância. Age com estratégia, mas o maior fator é o símbolo hipnótico cravado na cabeça, que distorce a percepção de quem observa, desviando ataques pra aliados. Fica mais irracional com o tempo.',
  '{Morte,Conhecimento}', 'Médio', 30, '6d6 mental', 65, '+15 (3◯, Percepção às Cegas)', '+15 (4◯)', 38, '+15 (3◯)', '+15 (4◯)', '+15 (3◯)', 400, 200, 'Corte, impacto e perfuração 10, Morte 20', 'Energia',
  '{"agi":4,"for":4,"int":3,"pre":3,"vig":3}', 'Atletismo +15 (4◯)', '12m | 8',
  '[{"nome":"Imunidades","descricao":"Dano balístico."},{"nome":"Físico Paranormal","descricao":"Pode saltar o dobro do deslocamento normal."},{"nome":"Instinto Mortal","descricao":"Machucado (200 PV ou menos), usa Hipnose como ação livre no início de cada turno e pode atacar 2x com garra no mesmo alvo."},{"nome":"Corpo Fechado","descricao":"Mirar na cabeça ignora a imunidade a dano balístico."}]',
  '[{"tipo":"Padrão","nome":"Agredir (Garra da Morte, corpo a corpo x2)","teste":"+25 (4◯)","dano":"4d10+20 Morte"},{"tipo":"Reação","nome":"Pancada Poderosa","descricao":"Crítico com a garra empurra o alvo 6m; colisão com objeto resistente ou outro ser causa 4d6 dano de impacto (a ambos, se for um ser)."},{"tipo":"Movimento","nome":"Comando","descricao":"Comanda um alvo em alcance curto a agir da forma mais eficiente possível (Vontade DT 29 evita) — replica um efeito básico do ritual Perturbação."},{"tipo":"Padrão","nome":"Hipnose","descricao":"Domina a mente de um alvo em alcance curto (Vontade DT 29 evita); controle telepático total exceto suicídio; repete o teste no fim de cada turno (+1 cumulativo); até 3 hipnotizados por vez; se o alvo enlouquecer, falha automática e domínio permanente."},{"tipo":"Completa","nome":"Reanimar Corpos","descricao":"1x/cena, reanima 2d4+2 corpos em alcance médio (usam a ficha de Esqueleto de Lodo), que atacam o ser mais próximo bestialmente até serem destruídos."}]',
  null, 13
),
(
  (select id from sources where slug = 'ordem_paranormal'), 'Ceifador Espiral', 380,
  'O rosto da Morte. Quem viveu experiências de quase morte às vezes relata algo mais intenso: uma visão que se distorce e espiraliza, revelando uma silhueta cada vez mais definida — todos os momentos da vida sendo devorados por uma criatura. Se o Ceifador se manifesta num ambiente, tudo é levado pela Morte — ninguém permanece vivo pra contar a história, nenhuma estrutura persiste — só cinzas e Lodo marcando o legado eterno.',
  '{Morte}', 'Grande', 45, '9d8 mental', null, '+20 (5◯, Percepção às Cegas)', '+20 (5◯)', 58, '+25 (5◯)', '+25 (5◯)', '+25 (5◯)', 999, 499, 'Dano 50', 'Energia',
  '{"agi":5,"for":5,"int":5,"pre":5,"vig":5}', null, '15m | 10',
  '[{"nome":"Imunidades","descricao":"Condições de paralisia, efeitos e dano de Morte."},{"nome":"Decepar","descricao":"Crítico com a foice reduz o alvo a 25 PV e tira 1 ponto permanente de Força/Agilidade/Vigor (aleatório); com 25 PV ou menos, morre na hora. Cada morte causada dá 50 PV temporários e +1d10 dano de foice até o fim da cena."}]',
  '[{"tipo":"Padrão","nome":"Agredir (Foice da Morte, corpo a corpo x2)","teste":"+40 (5◯)","dano":"5d10+20 Morte"},{"tipo":"Movimento","nome":"Transporte pelo Pó","descricao":"Dentro da área de Cinzas das Terras Desoladas, teletransporta-se pra outro espaço na área; pode atacar de foice como ação livre ao terminar."},{"tipo":"Completa","nome":"Contemplar a Espiral","dano":"10d10+30 mental (Vontade DT 43 reduz à metade)","descricao":"Todos em alcance médio que o veem; quem sofre fica imune até o fim da cena."},{"tipo":"Completa","nome":"Cinzas das Terras Desoladas","dano":"10d10+20 Morte + enjoado (Fortitude DT 43 reduz à metade e evita)","descricao":"Área de alcance longo vira terreno acelerado pelo tempo; terminar o turno na área causa mais 20 de dano de Morte."}]',
  'A espiral consome tudo — é o próprio tempo reverso; não dá pra pará-la. Quem quebra a espiral a transforma numa linha: infinita, mas com beiradas, e portanto com escapatória. Ao resolver, perde a resistência a dano, e qualquer área de Terras Desoladas vira terreno normal no fim do próximo turno.', 14
),
(
  (select id from sources where slug = 'ordem_paranormal'), 'Enraizado', 120,
  'A Morte infecta em especial áreas de alta biodiversidade — florestas — corrompendo-as e consumindo-as vagarosamente. Nem cadáveres putrefatos sepultados há anos escapam de virar cascas infectadas. Um enraizado nasce de um corpo enterrado perto de vegetação infestada pela Morte, invadido por raízes grossas e preenchido de Lodo que movimenta seus membros como um esqueleto de armadura de raízes entrelaçadas.',
  '{Morte}', 'Médio', 20, '4d6 mental', 50, '+10 (1◯, Percepção às Cegas)', '+10 (3◯)', 28, '+10 (3◯)', '+10 (3◯)', '+5 (1◯)', 140, 70, 'Corte, impacto e perfuração 10, Morte 20', 'Energia',
  '{"agi":3,"for":3,"int":1,"pre":1,"vig":3}', 'Atletismo +10 (3◯)', '9m | 6',
  '[{"nome":"Imortalidade","descricao":"Ao morrer, se desfaz numa poça de Lodo/galhos/raízes; retorna em 1d2 rodadas com 70 PV; 20+ de dano de fogo/Energia somado enquanto poça o destrói permanentemente."},{"nome":"Veneno Pútrido","descricao":"Primeiro dano do punho espinhento numa cena envenena; no início de cada turno, Fortitude DT 23 ou 4d12 dano de Morte (passar cura o veneno)."}]',
  '[{"tipo":"Padrão","nome":"Agredir (Punho Espinhento, corpo a corpo x2)","teste":"+15 (3◯)","dano":"2d8+8 impacto mais 2d12 Morte"}]',
  null, 15
),
(
  (select id from sources where slug = 'ordem_paranormal'), 'Escutado', 160,
  'Originado de alguém que escutou a "Melodia Espiral" — música paranormal proibida capaz de enlouquecer quem a ouve inteira. Corpo humanoide retorcido e magro, anda de forma quadrúpede invertida, com uma cabeça capaz de se desprender do corpo, deixando um rastro de Lodo vomitado. Aparenta ser imortal e é atraído a qualquer melodia — mas ao ouvir a "Spiralem Melodiam" específica que causou sua origem, fica extremamente agressivo, buscando destruir a fonte.',
  '{Morte,Energia}', 'Médio', 25, '4d8 mental', 55, '+10 (2◯, Percepção às Cegas)', '+10 (4◯)', 29, '+10 (3◯)', '+10 (4◯)', '+5 (2◯)', 290, 145, null, null,
  '{"agi":4,"for":3,"int":1,"pre":2,"vig":3}', null, '12m | 8',
  '[{"nome":"Imunidades","descricao":"Dano."},{"nome":"Multiplicação Melódica","descricao":"No início do turno, se estiver ouvindo a melodia de sua criação, manifesta uma cópia (145 PV, sem imunidade a dano) em alcance curto; cópias também têm essa habilidade e agem a partir do próximo turno; todas tentam eliminar quem toca a melodia."}]',
  '[{"tipo":"Padrão","nome":"Agredir (Mordida, corpo a corpo x2)","teste":"+20 (3◯)","dano":"3d6+10 perfuração"},{"tipo":"Padrão","nome":"Agredir (Cabeça Arremessada, distância x2, curto)","teste":"+15 (4◯)","dano":"1d10+10 impacto"},{"tipo":"Movimento","nome":"Vomitar Lodo","dano":"4d10+10 Morte + lento até fim da cena (Reflexos DT 25 reduz à metade e evita)","descricao":"1x/cena, na primeira rodada após ser manifestada, cada cópia despeja Lodo num alvo em alcance curto."}]',
  'Tocar a melodia exige ação padrão + Artes DT 25 por rodada (ou tocar um aparelho com a música). Enquanto toca, o escutado se multiplica; após 4 rodadas ininterruptas ouvindo, perde a imunidade a dano até o fim da cena e pode ser derrotado — mas em 4 rodadas de multiplicação (se nenhuma cópia for destruída) haverá 16 criaturas. Os agentes devem destruir cópias enquanto tocam, impedir que se multipliquem mais, e aguentar as 4 rodadas.', 16
),
(
  (select id from sources where slug = 'ordem_paranormal'), 'Esqueleto de Lodo', 20,
  'Cadáver consumido pela Morte, forma esquelética acinzentada com Lodo escorrendo dos orifícios, deixando um rastro que parece perseguir a criatura. Sons bizarros vêm de dentro do crânio — palavras sem sentido, rugidos invertidos numa voz rasgada. Sempre parece se regenerar após destruído, mas a regeneração pode ser desacelerada ou interrompida se o Lodo for queimado ou exposto a Energia.',
  '{Morte}', 'Médio', 14, '2d4 mental', 25, '+0 (Percepção às Cegas)', '+0 (2◯)', 14, '+0', '+5 (2◯)', '+0', 40, 20, 'Corte, impacto e perfuração 5, Morte 10', 'Energia',
  '{"agi":2,"for":2,"int":0,"pre":1,"vig":1}', null, '6m | 4',
  '[{"nome":"Imortalidade","descricao":"Ao morrer, vira poça de Lodo e ossos, retorna em 1d3 rodadas com 20 PV; dano de fogo/Energia na forma de poça o destrói permanentemente."}]',
  '[{"tipo":"Padrão","nome":"Agredir (Garras, corpo a corpo x2)","teste":"+5 (2◯)","dano":"2d6+2 corte"},{"tipo":"Completa","nome":"Espiral de Lodo","dano":"2d10 Morte (Reflexos DT 14 reduz à metade)","descricao":"Vira poça e se lança como espiral perfurante até 9m em linha reta; se reforma no fim do trajeto."}]',
  null, 17
),
(
  (select id from sources where slug = 'ordem_paranormal'), 'Marionete', 280,
  'Manifestação da tristeza, apatia e negação de um trauma — resquício de uma memória distorcida, uma possibilidade roubada, o momento que nunca aconteceu. Esqueleto retorcido preenchido de Lodo, resultado da rejeição do luto e da tentativa desesperada de trazer alguém de volta dos mortos. É possível reconhecer traços de quem já se foi ao observá-la — ceder à tentação pode ser a última coisa que você faz. Nada que foi levado pela Morte pode voltar ao que era.',
  '{Morte}', 'Médio', 35, '8d6 mental', 85, '+15 (5◯, Percepção às Cegas)', '+15 (3◯)', 40, '+10 (2◯)', '+15 (3◯)', '+20 (5◯)', 700, 350, 'Corte, impacto, perfuração e Morte 20', 'Energia',
  '{"agi":3,"for":5,"int":1,"pre":5,"vig":2}', null, '6m | 4',
  '[{"nome":"Movimento Passivo","descricao":"Apesar de lenta, não pode ter o deslocamento reduzido e ignora terreno difícil; não sofre dano/efeitos que dependam de tocar o chão."}]',
  '[{"tipo":"Padrão","nome":"Agredir (Foice Óssea, corpo a corpo x2)","teste":"+30 (5◯)","dano":"10d8+10 Morte"},{"tipo":"Reação","nome":"Reflexos Guiados por Corda","descricao":"1x/rodada, quando alguém fica adjacente, ataca com a foice."},{"tipo":"Completa","nome":"Ironia do Destino","descricao":"2 ataques de foice num adjacente; se acertar o 2º, agarra a vítima e pode se deslocar 6m carregando-a; enquanto agarra, divide o dano que sofre com a vítima."}]',
  null, 18
),
(
  (select id from sources where slug = 'ordem_paranormal'), 'Múmia Xipófaga', 240,
  'Evidências arqueológicas mostram registros do Outro Lado há milênios, mesmo no Antigo Egito, onde a mumificação em busca da imortalidade tinha resultados macabros. A obsessão pela vida eterna gerou histeria cultural do pavor à própria Morte. A origem exata é um mistério, mas o comportamento é macabro: quem é agarrado e absorvido até o fim da vida é fundido ao corpo da múmia, virando mais um ser amalgamado nas amarras da eternidade distorcida da Morte.',
  '{Morte}', 'Médio', 30, '6d8 mental', 75, '+10 (3◯, Percepção às Cegas)', '+15 (5◯)', 35, '+15 (4◯)', '+15 (5◯)', '+10 (3◯)', 400, 200, 'Corte, impacto e perfuração 10, Morte 20', 'Energia, fogo',
  '{"agi":5,"for":4,"int":2,"pre":3,"vig":4}', null, '9m | 6',
  '[{"nome":"Faixas da Permanência","descricao":"Reduzida a 0 PV, não morre — continua agindo até o fim do próximo turno; se não terminar esse turno com 1+ PV, morre."}]',
  '[{"tipo":"Padrão","nome":"Agredir (Garra Enfaixada, corpo a corpo x2)","teste":"+30 (4◯)","dano":"4d8+30 corte"},{"tipo":"Padrão","nome":"Agredir (Vomitar Lodo, distância x2, curto)","teste":"+25 (5◯)","dano":"3d6+30 Morte mais 3d8 mental"},{"tipo":"Livre","nome":"Agarrada Mumificadora","teste":"+30 (4◯)","descricao":"Ao acertar garra enfaixada, tenta agarrar; agarrado sofre 4d8+30 dano de Morte no início de cada turno, e a múmia recupera o mesmo tanto de PV; se reduzido a 0 PV assim, vira esqueleto de Lodo no início do seu turno."},{"tipo":"Padrão","nome":"Amalgamar","descricao":"Com 0 PV, amalgama um ser morto ou criatura de Morte adjacente — recupera 200 PV, passa a atacar 3x com garras, +5 dano por ataque; pode se amalgamar uma 2ª vez (mais 200 PV, 4 ataques, +10 dano total por ataque)."}]',
  null, 19
),
(
  (select id from sources where slug = 'ordem_paranormal'), 'Nidere', 320,
  'Origem em cultos milenares de povos nativos da América do Sul, virado lenda e depois folclore — "o lobo invertido" que caça acampantes na floresta. Manifesta-se só em ambientes selvagens sob condições extremamente específicas. Como um lobo enorme, atroz e desfigurado, corpo retorcido; poucos sobreviventes o descrevem como um vulto negro na noite, olhos vermelhos, rosnados distorcidos como invertidos. É o predador alfa das criaturas paranormais — impossível se preparar pra enfrentá-lo de frente. Ele sempre estará caçando você.',
  '{Morte,Sangue}', 'Grande', 35, '8d6 mental', 95, '+25 (6◯, Faro)', '+25 (5◯)', 50, '+25 (5◯)', '+25 (5◯)', '+15 (4◯)', 800, 400, 'Corte, impacto, perfuração e Morte 20', 'Energia',
  '{"agi":5,"for":5,"int":3,"pre":4,"vig":5}', 'Furtividade +23 (5◯), Sobrevivência +20 (5◯)', '24m | 18',
  '[{"nome":"Caçador Veloz","descricao":"Move-se no deslocamento normal sem penalidade em Furtividade."},{"nome":"Regeneração Acelerada","descricao":"Cura Acelerada 50 (perde ao resolver o Enigma de Medo)."},{"nome":"Senso de Direção Perfeito","descricao":"Nunca se perde; +◯◯ em Percepção e Sobrevivência (já contabilizado; perde ao resolver o Enigma de Medo)."}]',
  '[{"tipo":"Padrão","nome":"Agredir (Garra Invertida, corpo a corpo x2)","teste":"+35 (5◯)","dano":"4d10+40 Morte"},{"tipo":"Padrão","nome":"Agredir (Mordida Invertida, corpo a corpo)","teste":"+35 (5◯)","dano":"4d12+40 Morte"},{"tipo":"Livre","nome":"Reverter","descricao":"Quem sofre dano das garras invertidas fica enjoado até o fim do próximo turno."},{"tipo":"Livre","nome":"Rastrear e Abater","descricao":"+6d6 dano contra alvos desprevenidos."}]',
  'É preciso achar o covil (cavernas nas profundezas da floresta); enfrentá-lo lá o torna ainda mais mortal. É preciso entender a lógica distorcida dos restos ósseos de vítimas penduradas no covil. Ao destruir a origem, entra em fúria incontrolável: -10 Defesa, -◯◯ em testes de resistência, perde Regeneração Acelerada e Senso de Direção Perfeito, ficando suscetível a cair em armadilhas simples.', 20
),
(
  (select id from sources where slug = 'ordem_paranormal'), 'Sempiternal', 360,
  'É comum encontrar ocultistas com percepção deformada pelo Outro Lado — mas e se essa exposição fosse estendida por inúmeras gerações? Um sempiternal é o resultado de exposição gradual à Morte passada por gerações de uma civilização isolada. O que um dia foi humano hoje é uma figura esquelética retorcida, olhos pretos, pele acinzentada, emitindo sons invertidos que só outros distorcidos pela Morte compreendem. Não é mais humano — não bebe, não come, não dorme. Desenvolveu um sexto sentido: manipula a própria percepção do tempo.',
  '{Morte}', 'Médio', 40, '8d8 mental', null, '+20 (5◯, Percepção às Cegas)', '+25 (5◯)', 53, '+20 (4◯)', '+30 (5◯)', '+25 (5◯)', 990, 445, 'Corte, impacto e perfuração 20', 'Energia',
  '{"agi":5,"for":5,"int":4,"pre":5,"vig":4}', null, '12m | 8',
  '[{"nome":"Imunidades","descricao":"Condições de paralisia, dano e efeitos de Morte."},{"nome":"Toque Acelerador","descricao":"Dano dos dedos alongados envelhece 1d10 anos; 20+ anos = fraco até o fim da cena; 40+ = debilitado; 60+ = morte. Seres com afinidade de Morte são imunes."}]',
  '[{"tipo":"Padrão","nome":"Agredir (Dedos Alongados, corpo a corpo x4)","teste":"+40 (5◯)","dano":"4d10 Morte + envelhecimento (Toque Acelerador)"},{"tipo":"Movimento","nome":"Correntes de Lodo","dano":"20d6 Morte (Fortitude DT 40 reduz à metade)","descricao":"Projeta vinhas de Lodo em toda área de alcance médio; quem fica machucado é infectado (vulnerabilidade a Morte até o fim da cena); quem chega a 0 PV vira um enraizado."}]',
  null, 21
),
(
  (select id from sources where slug = 'ordem_paranormal'), 'Succ', 40,
  'Ser quadrúpede com patas pontudas, pele enrugada e acinzentada, dois buracos onde deveriam estar os pulmões, pescoço longo e invertebrado levando a uma boca circular com dentes em camadas. Busca sugar todo o ar dos pulmões da vítima — a sucção constante emite um som alto, facilmente confundido com um aspirador de pó.',
  '{Morte,Energia}', 'Médio', 15, '3d6 mental', 30, '+5 (Percepção às Cegas)', '+5 (4◯)', 20, '+0', '+10 (4◯)', '+5', 65, 32, 'Corte, impacto e perfuração 5, Morte 10', 'Energia',
  '{"agi":4,"for":2,"int":0,"pre":1,"vig":1}', null, '12m | 8',
  '[]',
  '[{"tipo":"Padrão","nome":"Agredir (Mordida, corpo a corpo)","teste":"+10 (4◯)","dano":"2d8+2 perfuração"},{"tipo":"Livre","nome":"Sucção","descricao":"Ao acertar mordida, prende os dentes no rosto e suga o ar; Fortitude DT 17 solta; falhar deixa inconsciente e, no início do próximo turno do succ, reduz a 0 PV e morrendo; enquanto prende, o succ só pode usar reações e seu deslocamento cai pra 3m; sofrer 10+ dano numa rodada faz o succ soltar qualquer vítima."}]',
  null, 22
),
(
  (select id from sources where slug = 'ordem_paranormal'), 'O Deus da Morte', 400,
  'Também conhecido como Parasita de Dimensões, entidade suprema que se manifesta consumindo a entropia — energia potencial e tempo de tudo que é vivo. Pode parasitar o corpo de alguém com exposição paranormal extremamente elevada dedicado à Morte. Comportamento totalmente apático — nada o interessa além de consumir tempo de vida. Não viaja pelo espaço, mas pelo tempo, podendo se manifestar em vários pontos da Realidade ao mesmo tempo. É a única coisa capaz de resolver o Enigma de Medo do Diabo. (Chefe único, Relíquia.)',
  '{Morte,Conhecimento}', 'Grande', 45, '10d8 mental', null, '+30 (5◯, Percepção às Cegas)', '+30 (6◯)', 60, '+35 (7◯)', '+35 (6◯)', '+35 (5◯)', 2000, 1000, 'Corte, impacto e perfuração 20', 'Energia',
  '{"agi":6,"for":6,"int":5,"pre":5,"vig":7}', null, '15m | 10',
  '[{"nome":"Imunidades","descricao":"Atordoado, condições de paralisia, dano e efeitos de Morte."},{"nome":"Potência de Morte","descricao":"+35 em perícias baseadas em Força/Vigor/Presença, +25 nas demais."},{"nome":"Senhor do Tempo","descricao":"No início de cada rodada, rola 1d20 e recebe um turno adicional na iniciativa correspondente."},{"nome":"Ciclo Infinito","descricao":"Recupera 50 PV no início de cada turno; ao chegar a 0 PV, vira poça de Lodo e no próximo turno se manifesta no cadáver mais próximo (ou de maior NEX ao alcance), recuperando todos os PV e curando todas as condições (perde essa capacidade ao resolver o Enigma de Medo)."}]',
  '[{"tipo":"Padrão","nome":"Agredir (Soco Espiral, corpo a corpo x2)","teste":"+45 (6◯)","dano":"5d10+50 Morte"},{"tipo":"Livre","nome":"Agarrão","teste":"+47 (6◯)","descricao":"Ao acertar soco espiral em alvo Médio ou menor, tenta agarrar."},{"tipo":"Livre","nome":"Controlar Relógio Interno","descricao":"No início de cada turno, encerra até 2 condições que o afetam."},{"tipo":"Movimento","nome":"Controlar Mortos","descricao":"Controla qualquer criatura de Morte em alcance longo, fazendo-a se mover e atacar."},{"tipo":"Movimento","nome":"Espiral Descendente","dano":"1 dano mental por ano envelhecido","descricao":"Acelera o tempo de um agarrado, paralisado sem poder agir; envelhece 3d20 anos."},{"tipo":"Padrão","nome":"Espiral Destrutiva","dano":"10d10+50 Morte (Fortitude DT 45 reduz à metade)","descricao":"Espiral de Morte de 12m de raio em alcance longo."}]',
  'O Deus da Morte é uma manifestação diferente das outras — provavelmente a mais próxima da verdadeira realidade que compreende sua manipulação completa do tempo. Ninguém sabe o suficiente sobre ele pra sequer supor um Enigma de Medo completo. No caso raro de alguém desejar enfrentá-lo, perde suas habilidades Ciclo Infinito e Senhor do Tempo quando seu Enigma de Medo for resolvido.', 23
);
