-- Bestiário Livro Base — Criaturas de Energia (11) + Anfitrião (chefe único) + Degolificada
-- (criatura de Medo, metamorfose por elemento). Fecha as 46 criaturas paranormais do Livro Base.

insert into creatures (source_id, name, vd, flavor_text, descritores, tamanho, presenca_dt, presenca_dano, presenca_nex_imune, percepcao, iniciativa, defesa, fortitude, reflexos, vontade, pv_maximo, pv_machucado, resistencias, vulnerabilidades, atributos, pericias, deslocamento, habilidades, acoes, enigma_medo, sort_order)
values
(
  (select id from sources where slug = 'ordem_paranormal'), 'Anárquico', 20,
  'Quando alguém morre em situações extremamente inoportunas e azaradas num ambiente com a Membrana danificada, o corpo é consumido pela entidade de Energia — oxigênio e líquidos substituídos pela surrealidade da entidade. Pele semi-transparente, veias e órgãos internos coloridos e brilhosos, olhos arregalados emitindo luz plasmática, boca distorcida num sorriso forçado e rasgado. Rápidos e imprevisíveis, movimentos erráticos difíceis de acertar.',
  '{Energia}', 'Médio', 14, '2d6 mental', 25, '-2◯ (Visão no Escuro)', '+5 (3◯)', 21, '+0', '+10 (3◯)', '-2◯', 30, 15, 'Energia 5', 'Conhecimento',
  '{"agi":3,"for":2,"int":0,"pre":0,"vig":1}', null, '9m | 6',
  '[{"nome":"Comportamento Errático","descricao":"No início do turno, rola 1d6 (se não puder agir, fica parado se contorcendo com resistência a dano 5 até o próximo turno): 1-2 pula/investe no personagem mais próximo. 3-4 projeta luz prismática num alvo em alcance médio: 2d8 dano de Energia + atordoado 1 rodada (Fortitude DT 14 reduz à metade e evita). 5 explosão: todos em alcance curto sofrem 2d6 dano de Energia (Reflexos DT 14 reduz à metade; adjacentes +1d6). 6 risada descontrolada + agride o mais próximo; até o fim do próximo turno fica desprevenido, mas seus ataques são imprevisíveis e não podem ser esquivados."}]',
  '[{"tipo":"Padrão","nome":"Agredir (Pancada Errática, corpo a corpo)","teste":"+5 (2◯)","dano":"2d12 impacto"}]',
  null, 36
),
(
  (select id from sources where slug = 'ordem_paranormal'), 'Anárquico Descontrolado', 120,
  'Quando o corpo de alguém com alta exposição paranormal é transformado pela Energia num anárquico após um desastre extremamente inoportuno, as possibilidades se potencializam numa forma ainda mais caótica: um anárquico descontrolado. Forma translúcida completamente alucinada, hiperativa e caótica, corpo vibrando e flutuando em euforia. Imprevisível — pode estourar o próprio corpo numa explosão de Energia quando não vê mais nenhuma possibilidade de causar caos.',
  '{Energia}', 'Médio', 21, '4d6 mental', 50, '+5 (2◯, Visão no Escuro)', '+10 (4◯)', 28, '+10 (3◯)', '+10 (4◯)', '+5 (2◯)', 120, 60, 'Balístico, corte e perfuração 10, Energia 20', 'Conhecimento',
  '{"agi":4,"for":3,"int":2,"pre":2,"vig":3}', null, '12m | 8',
  '[]',
  '[{"tipo":"Padrão","nome":"Agredir (Pancada Energética, corpo a corpo x2)","teste":"+15 (4◯)","dano":"4d12 impacto"},{"tipo":"Livre","nome":"Aceleração","dano":"4d12 Energia adicional","descricao":"Quem sofre dano da pancada entra em \"aceleração\" — no próximo turno, se fizer movimento+padrão ou ação completa, sofre o dano adicional."},{"tipo":"Movimento","nome":"Autodestruição","dano":"8d12 Energia (Reflexos DT 25 reduz à metade; adjacentes -◯◯ no teste)","descricao":"Concentra Energia e se autodestrói em todos em alcance curto; o anárquico descontrolado morre ao usar."}]',
  null, 37
),
(
  (select id from sources where slug = 'ordem_paranormal'), 'Anomalia', 380,
  'Uma manifestação paranormal caótica, um monstro que a Realidade tenta esconder atrás da menor das possibilidades pra que sua falta de lógica possa ser ignorada. Indescritível para quem vivenciou — forma não contida por barreiras físicas de um corpo compreensível. Não há sobreviventes registrados. Sempre presente: o medo de que, na próxima vez que você abrir uma porta, a anomalia te escolha.',
  '{Energia}', 'Médio', 45, '9d8 mental', null, '— (Visão no Escuro)', '—', null, '+15 (5◯)', '+15 (5◯)', '+15 (5◯)', 1000, 500, null, 'Conhecimento',
  '{"agi":null,"for":null,"int":5,"pre":5,"vig":null}', null, '0m | 0',
  '[{"nome":"Imaterial","descricao":"Corpo físico desprezível escondido atrás de uma imensidão de Energia; imune a dano/condições; não faz testes nem age como outras criaturas; a única forma de derrotá-la é resolvendo o Enigma de Medo."},{"nome":"Existência Impossível","descricao":"Só existe dentro de um objeto que abra por uma porta; manifesta enquanto a porta está aberta; persegue quem a manifestou, surgindo sempre que abrirem uma porta/compartimento."}]',
  '[{"tipo":"Livre","nome":"Romper Consciência","dano":"10d6 mental (Vontade DT 41 reduz à metade)","descricao":"No início do turno, sorteia um alvo em sua linha de visão; se enlouquecer com isso, é absorvido pela anomalia."},{"tipo":"Livre","nome":"Manipular Ondas da Existência","descricao":"No fim do turno, ativa/desativa/opera até 6 objetos tecnológicos em alcance médio, ou sobrecarrega-os causando 2d12 dano de Energia por objeto em todos na área (Reflexos DT 30 reduz à metade)."},{"tipo":"Completa","nome":"Manifestar o Impossível","descricao":"Invoca criaturas de Energia com VD somado até 240, em alcance curto, agindo a partir da próxima rodada com impulsos caóticos."}]',
  'A anomalia não deveria existir — é o próprio caos colapsando com a Realidade, sem lógica que a defina. A única forma de combatê-la é mergulhar nela pra entendê-la no Outro Lado. Ao resolver, vira um ser/objeto aleatório por 2d4 rodadas, perdendo a imunidade a dano/condições e usando as estatísticas dele (exceto PV).', 38
),
(
  (select id from sources where slug = 'ordem_paranormal'), 'Anomiático', 240,
  'Originado de um corpo humano completamente transformado pela Energia — quando alguém com exposição altíssima deveria virar um anárquico, o caos se multiplica infinitamente, distorcendo por completo noções de regras, leis e razão. Espectro da loucura, comportamento totalmente insano. Sobreviventes descrevem um vulto de luz que se teleporta desenfreadamente, rindo caoticamente enquanto flutua e se desintegra por toda parte, atacando de forma aleatória.',
  '{Energia}', 'Médio', 30, '6d8 mental', 75, '+10 (4◯, Visão no Escuro)', '+15 (5◯)', 41, '+10 (3◯)', '+20 (5◯)', '+15 (4◯)', 600, 300, 'Balístico, corte e perfuração 10, Energia 20', 'Conhecimento',
  '{"agi":5,"for":3,"int":1,"pre":4,"vig":3}', null, '18m | 12',
  '[]',
  '[{"tipo":"Padrão","nome":"Agredir (Garra Desintegradora, corpo a corpo x2)","teste":"+30 (5◯)","dano":"4d12+20 Energia"},{"tipo":"Livre","nome":"Comportamento Errático","descricao":"No início do turno, rola 1d6 três vezes e executa em ordem: 1-2 salta até 18m até o mais próximo, agride com garras se adjacente. 3 vira facho de Energia até ficar adjacente a um alvo aleatório. 4 parte do corpo explode: 4d12+20 (médio)/6d12+20 (curto)/8d12+20 (adjacente) dano de Energia (Reflexos DT 30 reduz à metade em médio/curto); perde 50 PV ao usar. 5 risada descontrolada: fica desprevenido até o próximo turno, mas ataques ficam imprevisíveis. 6 toca um adjacente: 10d12+20 dano de Energia (Fortitude DT 30 reduz à metade)."}]',
  null, 39
),
(
  (select id from sources where slug = 'ordem_paranormal'), 'Ciborgue', 80,
  'O avanço da tecnologia e obsessão com melhorias cibernéticas pode levar a resultados bizarros. Originado de um cientista seduzido pelo poder da tecnologia, tão obstinado com eficiência que amputou os próprios membros e os substituiu por mecanismos ativados por Energia paranormal. Muda de comportamento e forma de ataque a qualquer momento; contato físico é perigoso, capaz de liberar pulsos elétricos fortes o suficiente pra desacordar um adulto.',
  '{Energia,Sangue}', 'Grande', 15, '2d6 mental', 40, '+5 (2◯, Visão no Escuro)', '+10 (3◯)', 25, '+10 (3◯)', '+5 (3◯)', '+0 (2◯)', 160, 80, 'Balístico, corte e perfuração 10, Energia 20', 'Conhecimento',
  '{"agi":3,"for":3,"int":2,"pre":2,"vig":3}', null, '9m | 6',
  '[{"nome":"Imunidades","descricao":"Condições de paralisia."},{"nome":"Regeneração Energética","descricao":"Recupera 20 PV no início do turno (perde se perder 3+ estados de combate)."},{"nome":"Estado de Combate","descricao":"No início do turno, assume um dos 4 estados (Alpha/Beta/Gama/Delta), que define suas ações disponíveis; um estado deixa de estar disponível quando sua fraqueza é resolvida."}]',
  '[{"tipo":"Padrão (Alpha)","nome":"Agredir (Braço Laminado, corpo a corpo x2)","teste":"+10 (3◯), crítico 18","dano":"1d12+10 corte"},{"tipo":"Padrão (Beta)","nome":"Agredir (Punho Energizado, corpo a corpo)","teste":"+10 (3◯)","dano":"2d8+10 impacto"},{"tipo":"Completa (Beta)","nome":"Investida Energética","descricao":"Avança até 24m (18) + ataque de punho com +◯ e +2d8 dano (total 4d8+10), derruba (Fortitude DT 20 evita)."},{"tipo":"Padrão (Gama)","nome":"Agredir (Canhão, distância, longo)","teste":"+10 (3◯)","dano":"4d12+5 Energia"},{"tipo":"Padrão (Delta)","nome":"Agredir (Raio Energético, distância, médio)","teste":"+10 (3◯)","dano":"1d12+5 Energia"},{"tipo":"Movimento (Delta)","nome":"Criar Barreira","descricao":"+5 Defesa até o próximo turno."},{"tipo":"Movimento (Delta)","nome":"Reiniciar","descricao":"Encerra uma condição."},{"tipo":"Livre (Delta)","nome":"Desorientar","descricao":"Quem sofre dano do raio fica alquebrado (repetir = atordoado 1 rodada, Vontade DT 20 evita)."}]',
  'Cada estado tem uma fraqueza específica definida na criação (ex.: 15+ dano de um tipo num único ataque, ou exposição a substância/material específico) — só resolvível estando naquele estado; resolvida, não pode mais assumir esse estado. Sem nenhum estado, se desativa: Defesa 10, deslocamento 0m.', 40
),
(
  (select id from sources where slug = 'ordem_paranormal'), 'Infecticídio', 280,
  'O debate se um vírus é um "ser vivo" nunca foi resolvido — mas manifestações do Outro Lado podem tomar essa forma. Origina-se como vírus digital em dispositivos eletrônicos; infecta seres vivos, distorcendo suas formas físicas numa horda descontrolada de mente ensandecida e compartilhada. Corpos deformados, olhos manchados com cores pulsantes, dentes pontudos e brilhosos. Contágio por sangue/saliva ou como vírus digital via dispositivos. Só é exterminável eliminando todos os dominados e congelando seus corpos.',
  '{Energia,Sangue}', 'Enorme', 35, '8d6 mental', 85, '+10 (Visão no Escuro)', '+15 (3◯)', 25, '+20 (5◯)', '+15 (3◯)', '+15 (1◯)', 600, 300, 'Balístico, corte, perfuração e Energia 20', 'Conhecimento',
  '{"agi":3,"for":5,"int":1,"pre":1,"vig":5}', null, '9m | 6',
  '[{"nome":"Horda","descricao":"Sofre metade do dano de ataques/habilidades de alvo único, mas dobro de dano de área; sempre causa metade do dano mesmo errando (exceto se o defensor esquivou com reação)."}]',
  '[{"tipo":"Padrão","nome":"Agredir (Pancadas Infectadas, corpo a corpo x3)","teste":"+30 (5◯)","dano":"4d12+20 Energia"},{"tipo":"Livre","nome":"Infecção","descricao":"Quem sofre dano das pancadas é infectado pelo vírus (Fortitude DT 30 evita; passar dá imunidade até o fim da cena)."},{"tipo":"Reação","nome":"Consumação Insidiosa","descricao":"Ao reduzir alguém a 0 PV com pancadas, consome a vítima e recupera 50 PV."},{"tipo":"Completa","nome":"Atropelar","descricao":"Percorre até o dobro do deslocamento, passando pelo espaço de outros seres; ataca de pancada infectada cada ser nos espaços por onde passa."}]',
  null, 41
),
(
  (select id from sources where slug = 'ordem_paranormal'), 'Perturbado de Energia', 40,
  'Quando uma alma é enlouquecida de forma brusca e agressiva, a psique pode ser tão violentada que a percepção da Realidade se esvai antes mesmo de perceber que não está mais viva. Forma plasmática inconsistente e desesperada, mergulhada em confusão, que nem entende o que é. Se agarra a qualquer consciência próxima tentando compartilhar e aliviar sua discórdia mental.',
  '{Energia}', 'Médio', 15, '2d8 mental', 30, '-2◯ (Visão no Escuro)', '+10 (4◯)', 19, '-2◯', '+10 (4◯)', '-2◯', 60, 30, 'Balístico, corte e perfuração 5, Energia 10', 'Conhecimento',
  '{"agi":4,"for":1,"int":0,"pre":0,"vig":0}', null, '9m | 6',
  '[]',
  '[{"tipo":"Padrão","nome":"Agredir (Toque Plasmático, corpo a corpo x2)","teste":"+10 (4◯)","dano":"2d12 Energia"},{"tipo":"Livre","nome":"Implantar Confusão","teste":"+10 (4◯)","descricao":"1x/rodada, tenta agarrar quem acabou de sofrer dano do toque; conseguindo, implanta imagens traumáticas: 2d8 dano mental (Vontade DT 15 reduz à metade) + vulnerabilidade a Energia até o fim da cena."}]',
  null, 42
),
(
  (select id from sources where slug = 'ordem_paranormal'), 'Sukkalgir', 160,
  'Alma torturada pelo fogo — as sukkal se originaram na antiga Suméria quando textos eram cravados com brasa ardente na pele de vítimas, registrando os feitos e massacres de seu captor. Destinada a sofrer pela agonia do fogo que tomou seu corpo pela eternidade, emite um grito enlouquecedor constante. Corpo de Energia como labareda de cores impossíveis, pairando acima do chão, com escritas macabras flutuando pela pele caoticamente.',
  '{Energia,Conhecimento}', 'Médio', 25, '4d8 mental', 55, '+10 (3◯, Visão no Escuro)', '+10 (3◯)', 34, '+5 (2◯)', '+10 (3◯)', '+15 (3◯)', 220, 110, 'Impacto e Energia 10', 'Conhecimento',
  '{"agi":3,"for":2,"int":3,"pre":3,"vig":2}', null, 'Voo 18m | 12',
  '[{"nome":"Imunidades","descricao":"Dano balístico, de corte e de perfuração."},{"nome":"Aura Desesperada","descricao":"Quem começa o turno em alcance curto sofre 2d12 dano mental (Vontade DT 25 reduz à metade)."},{"nome":"Espírito Plasmático","descricao":"Parcialmente intangível, atravessa obstáculos sólidos."}]',
  '[{"tipo":"Padrão","nome":"Agredir (Mordida do Outro Lado, corpo a corpo x2)","teste":"+15 (3◯)","dano":"2d12 mental"},{"tipo":"Livre","nome":"Agarrão","teste":"+15 (3◯)","descricao":"Ao acertar mordida num alvo Médio ou menor, tenta agarrar."},{"tipo":"Completa","nome":"Grito de Desespero","dano":"3d12 mental (Vontade DT 20 reduz à metade; cobertura dá +5 no teste)","descricao":"Todos em alcance médio."}]',
  null, 43
),
(
  (select id from sources where slug = 'ordem_paranormal'), 'Telopsia', 340,
  'A lenda do filme amaldiçoado: uma fita VHS que contém uma gravação misteriosa e terrível, causando morte aterrorizante a quem assiste pouco tempo depois. Origem indeterminada, mas sempre conectada à criatura que a acompanha: um homem bizarro de sobretudo preto, corpo esquelético, cabeça similar a uma televisão antiga transmitindo imagens perturbadoras. Quem assistiu ao filme é eventualmente encontrado pela criatura — que passa a "assisti-los", distorcendo e desintegrando suas formas.',
  '{Energia,Morte}', 'Médio', 40, '10d6 mental', 99, '+25 (5◯, Visão no Escuro)', '+20 (4◯)', 48, '+15 (2◯)', '+20 (4◯)', '+25 (5◯)', 560, 280, 'Balístico, corte, perfuração e Energia 20', 'Conhecimento',
  '{"agi":4,"for":2,"int":3,"pre":5,"vig":2}', 'Furtividade +20 (4◯)', '12m | 8',
  '[{"nome":"Imunidades","descricao":"Condições de paralisia."}]',
  '[{"tipo":"Padrão","nome":"Agredir (Toque Desintegrador, corpo a corpo x3)","teste":"+35 (4◯)","dano":"6d12+30 Energia"},{"tipo":"Movimento","nome":"Viajar pela Tela","descricao":"Desmaterializa e rematerializa em outra tela/visor em alcance longo, depois desloca 9m."},{"tipo":"Padrão","nome":"Tela Zumbificadora","dano":"6d6 mental + confusos até o fim da cena (Vontade DT 30 reduz o dano à metade e evita a condição)","descricao":"Projeta imagens enlouquecedoras em alcance médio; quem já está confuso e falha fica também fascinado."},{"tipo":"Completa","nome":"Prender na Tela","descricao":"Desintegra um alvo em alcance curto e o materializa dentro da tela (Fortitude DT 30 evita); preso fica paralisado, 2d12 dano mental no início de cada turno; sempre que o telopsia sofrer 50+ dano num turno, o preso pode repetir Fortitude pra escapar."}]',
  'A única forma teorizada de derrotá-lo é destruir a própria fita amaldiçoada — exige investigar as vítimas pra encontrá-la. Destruindo a fita, o telopsia vai a 0 PV e é destruído; senão, mesmo derrotado em combate, é questão de tempo até retornar.', 44
),
(
  (select id from sources where slug = 'ordem_paranormal'), 'Tempestuoso', 360,
  'Tempestade do caos — criatura disforme manifestada em turbilhões descontrolados, causando transformação e estrago a tudo que toca. Como uma nuvem de pura Energia, uma supernova implodindo em forma humanoide, em constante transformação, contida só por tecnologia incompreensível de cabos metálicos. Só surge em ambientes com a Membrana extremamente danificada, em condições muito específicas (usinas radioativas abandonadas); seus efeitos perduram muito tempo depois, como radiação paranormal mais perigosa que a nuclear.',
  '{Energia}', 'Médio', 40, '8d8 mental', null, '+20 (5◯, Visão no Escuro)', '+25 (5◯)', 56, '+20 (4◯)', '+30 (5◯)', '+25 (5◯)', 950, 475, 'Balístico, corte, perfuração e Energia 20', 'Conhecimento',
  '{"agi":5,"for":4,"int":2,"pre":5,"vig":4}', null, '24m | 12',
  '[{"nome":"Imunidades","descricao":"Condições de paralisia."},{"nome":"Aura Radioativa","descricao":"Quem começa turno em alcance curto sofre 2d20+20 dano de Energia (Fortitude DT 40 reduz à metade)."},{"nome":"Espectro Radioativo","descricao":"Ataques corpo a corpo alcançam alcance curto."}]',
  '[{"tipo":"Padrão","nome":"Agredir (Garras Radioativas, corpo a corpo x2, alcance curto)","teste":"+40 (5◯)","dano":"4d20+20 Energia"},{"tipo":"Livre","nome":"Raio de Energia Radioativa","dano":"4d20+20 Energia (Reflexos DT 40 reduz à metade)","descricao":"Ao acertar 2 garras no mesmo alvo, projeta um raio dele até outro alvo em alcance médio."},{"tipo":"Completa","nome":"Expandir em Radiação","dano":"10d20+20 Energia (Reflexos DT 40 reduz à metade)","descricao":"Todos em alcance longo; o próprio tempestuoso perde 100 PV ao usar."}]',
  null, 45
),
(
  (select id from sources where slug = 'ordem_paranormal'), 'Viajante', 200,
  'O viajante das Polaroids — criatura maligna e cruel que distorce lentamente as memórias de um alvo, se transportando através de fotografias e consumindo o rosto de todos os registrados nelas. Corpo esbranquiçado, membros alongados, cabeça com incontáveis rostos terríveis mesclados. Fisicamente invisível, anda em paredes e tetos. Mata rasgando o rosto da vítima pelas extremidades da boca. Não se satisfaz com carne — busca memórias, arrancando o cérebro pra explorá-lo.',
  '{Energia,Conhecimento}', 'Médio', 20, '6d6 mental', 60, '+15 (4◯, Visão no Escuro)', '+15 (4◯)', 34, '+10 (2◯)', '+15 (4◯)', '+15 (4◯)', 360, 180, 'Balístico, corte e perfuração 10, Energia 20', 'Conhecimento',
  '{"agi":4,"for":2,"int":3,"pre":4,"vig":2}', null, '9m | 6 (Escalada 9m | 6)',
  '[{"nome":"Invisibilidade Permanente","descricao":"Camuflagem total, +15 Furtividade; quem não pode vê-lo fica desprevenido contra seus ataques."}]',
  '[{"tipo":"Padrão","nome":"Agredir (Pancada, corpo a corpo x2)","teste":"+15 (4◯)","dano":"2d12+10 impacto"},{"tipo":"Livre","nome":"Agarrão","teste":"+15 (2◯)","descricao":"Ao acertar pancada num alvo Médio ou menor, tenta agarrar."},{"tipo":"Completa","nome":"Devorar Memória","dano":"4d12 mental (Vontade DT 29 reduz à metade e evita)","descricao":"Entra na mente de um agarrado e devora memórias: esquece completamente uma pessoa; cada vítima perturbada assim aumenta o dano da pancada em +1d12 até o fim da cena."}]',
  'A única forma de enxergá-lo é fotografá-lo com dispositivos de captura de imagem — capturar sua existência numa imagem sem que esteja viajando através dela o distrai, tornando-o visível por alguns segundos. Ao resolver, perde a Invisibilidade Permanente até o início do próximo turno de quem capturou a imagem.', 46
),
(
  (select id from sources where slug = 'ordem_paranormal'), 'Anfitrião', 400,
  'Nota de extração: o valor de VD apareceu ambíguo no PDF ("0413", sobreposição de colunas) — segue o padrão de VD 400 dos demais chefes únicos, mas pode ser 413. PV = 1413 (confirmado pelo cálculo do machucado: 706). Descrição não capturada em detalhe — criatura de Energia/Conhecimento associada a teatro, caos e irracionalidade; sua imagem retrata cinco "atores" (Amphitruo, Aeneas, Liber, Silenus, Plautus). (Chefe único, múltiplas fases.)',
  '{Energia,Conhecimento}', 'Médio', 45, '10d8 mental', null, '+25 (6◯, Visão no Escuro)', '+35 (7◯)', 59, '+25 (5◯)', '+35 (7◯)', '+25 (6◯)', 1413, 706, null, 'Conhecimento',
  '{"agi":7,"for":5,"int":6,"pre":6,"vig":5}', null, '12m | 8',
  '[{"nome":"Imunidades","descricao":"Condições de paralisia, dano e efeitos de Energia."},{"nome":"Transformar a Morte","descricao":"É a única coisa capaz de enfrentar a onipresença temporal do Deus da Morte e resolver seu Enigma de Medo."},{"nome":"Potência de Energia","descricao":"+35 em testes de Agilidade/Intelecto, +25 nos demais."},{"nome":"Ato 1","descricao":"Inicia o combate dividido em 5 facetas (Amphitruo, Aeneas, Liber, Silenus, Plautus), cada uma com as mesmas estatísticas mas 250 PV e RD 20 próprios, só podendo usar habilidades com seu nome; destruídas todas, retorna à forma única e inicia o Ato 2."},{"nome":"Ato 2","descricao":"Forma única com todos os PV recuperados, usando todas as habilidades das 5 facetas, com 3 ações padrão por rodada (desde que diferentes); ativa Trilha Sonora (todos em alcance longo sofrem 2d10 dano mental no início de cada turno do Anfitrião) e Roleta Maluca (1d6 por ser em alcance longo no início do turno, cumulativo se repetido: 1 -5 Defesa até fim da cena; 2 ação sem sentido ou 4d10 dano mental no fim do turno; 3 4d20 dano de Energia; 4 -◯ Pontaria até fim da cena; 5 -◯ Luta até fim da cena; 6 nada)."}]',
  '[{"tipo":"Padrão","nome":"Teatro (Amphitruo)","dano":"10d6 mental (Artes DT 35 ou Vontade DT 45 evita)","descricao":"Envia texto incompreensível à mente do alvo, que deve decorar e recitar em segundos."},{"tipo":"Padrão","nome":"Queimar (Aeneas)","dano":"10d6+20 Energia (Reflexos DT 45 reduz à metade)","descricao":"Cone de chamas em alcance médio."},{"tipo":"Padrão","nome":"Agredir — Corte Caótico (Liber, corpo a corpo)","teste":"+45 (7◯)","dano":"3d12+20 Energia","descricao":"Livre — Romance Forçado: ao acertar, escolhe outro ser visível; os dois decidem entre si quem sofre o dano."},{"tipo":"Padrão","nome":"Agredir — Lança e Adaga (Plautus, corpo a corpo x2)","teste":"+45 (7◯)","dano":"2d12+20 Energia","descricao":"Livre — Eu Sou o Caos: ao acertar um desprevenido/flanqueado, +4d12 dano de Energia."},{"tipo":"Padrão","nome":"Agredir — Corte de Água (Silenus, corpo a corpo)","teste":"+45 (7◯)","dano":"5d12+20 Energia","descricao":"Livre — Afogamento: quem sofre esse dano fica asfixiado (Fortitude DT 35 evita; repetível no fim de cada turno)."},{"tipo":"Movimento","nome":"Teletransporte","descricao":"Move-se pra outro ponto em alcance médio."}]',
  'Personificação do caos e irracionalidade, capaz de transformar tudo que toca de forma abstrata e incompreensível. A única forma justa de enfrentá-lo é sob a proteção soberana do Equilíbrio, oferecida apenas pela Máscara do Desespero. Ao resolver, perde a imunidade a dano.', 47
),
(
  (select id from sources where slug = 'ordem_paranormal'), 'Degolificada', 320,
  'Uma das criaturas mais temidas — poucos encontraram uma degolificada e viveram pra contar. Manifestação direta do Outro Lado formada por todos os elementos paranormais conhecidos. Figura humanoide flutuando a centímetros do chão, corpo retorcido e dilacerado; um cabelo preto liso e enorme cresce da cabeça até o chão, se movendo com vontade própria; atrás dos fios, um rosto com olhos ausentes e uma boca costurada pela própria pele. Conectada a tragédias envolvendo crianças/adolescentes mortos cruelmente em rituais. "Se você vir longos cabelos pretos flutuando em sua direção... CORRA." (Criatura de Medo, metamorfose por elemento.)',
  '{Energia,Conhecimento,Sangue,Morte}', 'Médio', 40, '9d6 mental', 95, '+15 (4◯, Percepção às Cegas)', '+0 (3◯)', 45, '+20 (4◯)', '+15 (3◯)', '+25 (4◯)', 850, 425, null, null,
  '{"agi":3,"for":5,"int":3,"pre":4,"vig":4}', null, '6m | 4',
  '[{"nome":"Criatura de Medo","descricao":"Imune a dano até que se resolva o mistério de sua origem."},{"nome":"Metamorfose — Energia → Degolificada Conturbada","descricao":"Ao enlouquecer um alvo; vira espectro de Energia, atravessa paredes, ignora coberturas, dano vira de Energia; ganha resistência a Energia 20."},{"nome":"Metamorfose — Sangue → Degolificada Devoradora","descricao":"Ao matar um alvo e mantê-lo agarrado até o próximo turno, absorve-o; ganha ataque adicional de mordida (Teste +35, 5◯ · 10d10+20 Sangue) e resistência a Sangue 20."},{"nome":"Metamorfose — Morte → Degolificada Decrépita","descricao":"Após 3 erros consecutivos de ataque contra ela; vira forma esquelética de Lodo preto; deslocamento sobe pra 12m (8), resistência a Morte 20, e os cabelos viram Lodo capazes de agarrar (ação de movimento, alcance curto, Reflexos DT 35 evita)."},{"nome":"Metamorfose — Conhecimento → Degolificada Gnóstica","descricao":"Ao receber a resposta errada na tentativa de resolver seu enigma; sigilos dourados de Conhecimento aparecem ao redor; no fim de cada turno dela, o alvo visível mais próximo tem uma alucinação — 4d6 dano mental + atordoado até o fim do próximo turno (Vontade DT 35 reduz o dano à metade e evita a condição)."}]',
  '[{"tipo":"Padrão","nome":"Agredir (Pancada, corpo a corpo x2)","teste":"+35 (5◯)","dano":"8d8+20 impacto"},{"tipo":"Livre","nome":"Agarrar e Estrangular","teste":"+35 (5◯)","descricao":"Ao acertar pancada num alvo Médio ou menor, tenta agarrar; agarrado também fica asfixiado; até 2 agarrados por vez."},{"tipo":"Livre","nome":"Grito Rasgado","dano":"4d10+10 mental + efeito aleatório (Vontade DT 35 reduz o dano à metade e evita o efeito)","descricao":"1x/cena, rompe a vedação da boca; todos em alcance médio; efeito 1d4: 1 surdo permanente dos dois ouvidos; 2 surdo permanente de um; 3 surdo dos dois até o fim da cena; 4 surdo de um até o fim da cena."},{"tipo":"Movimento","nome":"Desfiguramento Capilar","dano":"10d6+20 perfuração (Fortitude DT 35 reduz à metade) + 6d10 mental (Vontade DT 35 reduz à metade)","descricao":"Usa os cabelos pra penetrar orifícios faciais de agarrados."}]',
  'Precisa ser confrontada com a causa de sua morte, de modo que não possa escapar do confronto — só assim perde a imunidade a dano.', 48
);
