-- Bestiário Sobrevivendo ao Horror — 12 criaturas paranormais (Cap. 3).
-- Notação de bônus deste livro usa "N1d20+K" (N reservas de esforço + K bônus fixo);
-- mantida como texto nos campos de teste/perícia/defesas pra não perder informação.

insert into creatures (source_id, name, vd, flavor_text, descritores, tamanho, presenca_dt, presenca_dano, presenca_nex_imune, percepcao, iniciativa, defesa, fortitude, reflexos, vontade, pv_maximo, pv_machucado, resistencias, vulnerabilidades, atributos, pericias, deslocamento, habilidades, acoes, enigma_medo, sort_order)
values
(
  (select id from sources where slug = 'sobrevivendo_ao_horror'), 'Sepultado', 20,
  'Caixão/sarcófago amaldiçoado que emite batidas rítmicas de dentro de sepulturas — o som de alguém enterrado vivo eternamente tentando escapar. Membros ósseos deformados (de um ou vários corpos fundidos na maldição) escapam pelas rachaduras. Pode passar despercebido como mobília num cemitério/mausoléu.',
  '{Morte}', 'Médio', 15, '2d4 mental', 25, '+0 (Percepção às Cegas)', '+0', 16, '3d20+5', '+0', '+0', 50, 25, 'Balístico, corte, impacto e perfuração 5, Morte 10', 'Energia',
  '{"agi":1,"for":3,"int":0,"pre":1,"vig":3}', 'Furtividade +1d20+10', '9m | 6 · Escalada 9m | 6',
  '[{"nome":"Membros Longos","descricao":"Alcance natural 3m (apesar de Médio)."},{"nome":"Parte do Cenário","descricao":"Em forma de caixão, +10 Furtividade (quase indistinguível de mobília); treinado em Ocultismo procurando ativamente ameaças pode notar com teste DT 20 como reação."}]',
  '[{"tipo":"Padrão","nome":"Agredir (Dedos Ósseos, corpo a corpo x3)","teste":"3d20+5","dano":"1d6+5 corte"},{"tipo":"Livre","nome":"Agarrão","teste":"3d20+5","descricao":"Ao acertar dedos ósseos, tenta agarrar."},{"tipo":"Padrão","nome":"Bater Desesperado","descricao":"Som ouvido a até 90m; a até 9m, todos (pessoas/animais) ficam atordoados 1 rodada (Vontade DT 14 reduz pra abalado 1 rodada); quem passa fica imune até o fim da cena."},{"tipo":"Completa","nome":"Tragar","dano":"2d4 dano mental ao ser tragado e no início de cada turno preso (Vontade DT 14 reduz à metade)","descricao":"Se agarrando ser Médio ou menor, puxa pra dentro do caixão e fecha; agarrado + imóvel; só liberta destruindo o Sepultado; só traga 1 por vez."}]',
  null, 68
),
(
  (select id from sources where slug = 'sobrevivendo_ao_horror'), 'Mescla', 60,
  'Fusão grotesca entre pessoa e inseto — alguém que se expôs deliberadamente a vermes/larvas/parasitas buscando uma "revelação natural" do que é ser humano. Membros longos terminados em garras, pele mesclada entre carapaça de inseto e carne exposta, olhos substituídos por buracos com larvas; cheiro insuportável. Vista às vezes como silhueta voadora (asas de mosca gigante) ou como centopeia alongada. Intenção: proliferar e consumir.',
  '{Sangue}', 'Grande', 20, '3d6 mental', 35, '1d20+5 (Faro, Percepção às Cegas alcance longo)', '3d20+10', 21, '2d20+5', '3d20+10', '1d20+5', 100, 50, 'Balístico, corte, perfuração 10, Sangue 20', 'Morte, fogo e frio',
  '{"agi":3,"for":3,"int":1,"pre":1,"vig":2}', 'Acrobacia +3d20+10, Atletismo +3d20+10, Furtividade +3d20+8', '12m | 8 · Escalada 12m | 8 · Voo 9m | 6',
  '[{"nome":"Fluidos Repugnantes","descricao":"Dano corpo a corpo/curto nela, ou sofrer dano de Sangue dela, causa enjoado 1 rodada (Fortitude DT 20 evita)."},{"nome":"Percepção Multifacetada","descricao":"Não pode ser flanqueada nem surpreendida."},{"nome":"Imunidades","descricao":"Químico."}]',
  '[{"tipo":"Padrão","nome":"Agredir (Garras, corpo a corpo x2)","teste":"3d20+10","dano":"2d6+5 corte"},{"tipo":"Padrão","nome":"Agredir (Cuspe Ácido, distância, curto)","teste":"3d20+10","dano":"3d12 Sangue"},{"tipo":"Livre","nome":"Vomitar Ácido","dano":"+1d12 Sangue","descricao":"Acertando os 2 ataques de garra na mesma ação num alvo."},{"tipo":"Reação","nome":"Agarrão","teste":"3d20+12","descricao":"Acertando os 2 ataques de garra na mesma ação, tenta agarrar."},{"tipo":"Completa","nome":"Camuflagem Sobrenatural","descricao":"Não sendo vista por ninguém, fica imóvel + camuflagem total, +10 Furtividade."},{"tipo":"Completa","nome":"Incubar Ovos","teste":"3d20+10","descricao":"Agarrando um ser, ferrão oculto na língua; acertando, incuba 1d4 ovos (Fortitude DT 5+5 por ovo evita); incubado sofre versão modificada de Sangue Quente com Estágio IV — ao alcançar, nasce uma nova Mescla de dentro da vítima, matando-a."},{"tipo":"Completa","nome":"Investida Insectoide","descricao":"De local acima de um alvo em alcance médio, salta e aterrissa adjacente; conta como investida, mas ataca com as 2 garras (ambas com bônus de investida)."}]',
  null, 69
),
(
  (select id from sources where slug = 'sobrevivendo_ao_horror'), 'Espectro Inesquecido', null,
  'TEMPLATE, não uma criatura fixa — ecos das memórias da Realidade que vazam através da Membrana fragilizada; não são almas ou fantasmas de verdade, só repetições distorcidas. Toda história envolve os "Marcados" (NPCs específicos escolhidos misteriosamente pelo Outro Lado). Quando um Marcado sem destino predeterminado morre, pode gerar um Espectro Inesquecido: versão translúcida/espectral/distorcida dele, existindo e não existindo ao mesmo tempo, até que seu passado seja descoberto por outro Marcado com a mesma Marca.

Aplicado sobre a ficha do NPC "Marcado" original, usando o NEX dele: vira criatura de Energia; VD = 4 × NEX do Marcado; tamanho inalterado. Ganha Presença Perturbadora (DT e dano mental conforme faixa de VD — tabela abaixo); seres com NEX 20+ acima do NEX original do Marcado são imunes. Sentidos: +5 Iniciativa e Percepção, Percepção às Cegas, Visão no Escuro. Defesa/Fortitude/Reflexos/Vontade: bônus da tabela + 1d20+5. PV = PV do Marcado × multiplicador da tabela; resistência a balístico/corte/impacto/perfuração/Conhecimento/Morte = valor da tabela; resistência a Energia = esse valor +10; vulnerabilidade a Conhecimento. Atributos e Perícias iguais ao Marcado (Furtividade sobe 1 grau: treinado→veterano; veterano já expert vira +5). Deslocamento/Habilidades/Ações/Ataques iguais ao Marcado (NEX original usado pra qualquer efeito baseado em NEX); ataques recebem +1d20+5 no teste e o bônus de dano da tabela; todo dano vira dano de Energia. PE = PE do Marcado; não tem Sanidade. Ação Completa universal "Aterrorizar": pessoas/animais em alcance curto sofrem dano mental da tabela (Vontade da tabela reduz à metade).

Tabela 3.1 (VD → DT/Dano mental/Defesa+Resist./Multiplicador PV/Dano extra): 20-40 → 15 / 2d8 / +2 / x2 / +5. 60-100 → 20 / 3d8 / +5 / x3 / +10. 120-160 → 25 / 4d8 / +10 / x4 / +20. 180-300 → 35 / 6d8 / +15 / x5 / +30. 320-400 → 40 / 8d8 / +20 / x6 / +40.

Exemplo de aplicação (Marcado NEX 55% → Espectro VD 220): Marcado original Pessoa Médio, Percepção +2d20, Defesa 12, PV 68/34, PE 66, Sanidade 56, AGI2/FOR1/INT3/PRE3/VIG2, perícias Ciências/Medicina/Intuição, poderes Balística Avançada/Conhecimento Aplicado/Eclético/Investigação Científica/Na Trilha Certa/Pensamento Ágil/Perito/Equipe de Trauma/Paramédico, armado com faca e pistola sinalizadora. Espectro: VD 220, Energia (descritores adicionais Conhecimento, Morte), Criatura Médio, Presença Perturbadora DT 35/6d8 mental/NEX 75%+ imune, Percepção 3d20+15, Iniciativa 3d20+5, Percepção às Cegas, Visão no Escuro, Defesa 27, Fortitude 3d20+5, Reflexos 3d20+15, Vontade 4d20+15, PV 340/170, Resistências balístico/corte/impacto/perfuração/Conhecimento/Morte 15 e Energia 25, Vulnerabilidade Conhecimento, mesmos atributos/perícias (Furtividade +1 grau), mesmos poderes, ataques "Lâmina Espectral" (corpo a corpo, Teste 2d20+10 crítico 19, Dano 1d4+31 Energia) e "Pistola Sinalizadora Espectral" (distância curto, Teste 3d20+15, Dano 2d6+32 Energia), Aterrorizar 2d8 dano mental alcance curto (Vontade DT 15 reduz à metade).',
  '{Energia}', null, null, null, null, null, null, null, null, null, null, null, null, null, null,
  '{}', null, null,
  '[{"nome":"Ver flavor_text","descricao":"Template completo (fórmulas por faixa de VD, exemplo de aplicação) documentado no flavor_text — não tem stat block fixo."}]',
  '[]',
  'Cada Espectro Inesquecido surge de uma morte específica e imprevisível de um Marcado — as condições pra dissipá-lo são únicas por manifestação, ligadas à personalidade/escolhas/ações da pessoa em vida (distorcidas pelo Outro Lado). Não há regra fixa; o mestre define caso a caso.', 70
),
(
  (select id from sources where slug = 'sobrevivendo_ao_horror'), 'Derretido', 80,
  'Massa amorfa de carne gelatinosa, órgãos e restos mortais cozinhando num ácido borbulhante — absorve, derrete e expande sem forma fixa nem empatia. Consegue assumir silhuetas temporárias do que já absorveu. Move-se por frestas e encanamentos, surpreendendo vítimas.',
  '{Sangue,Energia}', 'Enorme', 20, '4d6 mental', 40, '1d20+5 (Percepção às Cegas)', '1d20+5', 23, '4d20+10', '1d20+5', '1d20+5', 140, 70, 'Sangue 20', 'Morte, fogo e químico',
  '{"agi":1,"for":4,"int":0,"pre":1,"vig":4}', 'Enganação +1d20, Furtividade +1d20', '9m | 6 · Escalada 9m | 6',
  '[{"nome":"Amorfo","descricao":"Atravessa qualquer fresta por onde água passaria (fica lento enquanto espreme); não é restringido por obstáculos físicos."},{"nome":"Liberdade de Espaço","descricao":"Invade quadrados ocupados por outras criaturas; criaturas passam pelo espaço dele mas é terreno difícil."},{"nome":"Matéria Nociva","descricao":"Quem entra ou começa turno na área dele sofre 6d6 dano de Sangue + lento e enjoado 1 rodada (Fortitude DT 20 reduz à metade e evita a condição), 1x/rodada por criatura."},{"nome":"Imunidades","descricao":"Balístico, corte, impacto e perfuração."}]',
  '[{"tipo":"Padrão","nome":"Arrastar Repulsivo","dano":"4d6 Sangue + caído","descricao":"Até o próximo turno, ao se mover, arrasta seres/objetos da área à escolha (Atletismo DT 20 evita)."},{"tipo":"Padrão","nome":"Rastro Corrosivo","dano":"1d6 ácido (1x/rodada por criatura)","descricao":"Até o próximo turno, deixa rastro ácido (terreno difícil) por onde passa; quem entra/começa turno na área sofre o dano."},{"tipo":"Padrão","nome":"Simular Corpo","descricao":"Molda silhueta de pessoa/animal/objeto; em penumbra/escuridão, +10 Furtividade pra esconder e Enganação pra disfarce."},{"tipo":"Completa","nome":"Consumir","descricao":"Consome ser em sua área, inconsciente com 0 PV; recupera 20 PV e dissolve a vítima por completo."},{"tipo":"Completa","nome":"Deslizar Nojento","descricao":"Fora de espaço apertado, percorre o triplo do deslocamento."}]',
  null, 71
),
(
  (select id from sources where slug = 'sobrevivendo_ao_horror'), 'O Uivar', 100,
  'Anomalia climática paranormal mais que uma criatura convencional — nevasca incontrolável que transforma vítimas em esculturas de gelo disformes, roubando seu calor e "essência". Presença sentida pelo vazio (invisível), silhueta desenhada pela distorção da neve ao redor; som como dezenas de gritos misturados ao vento.',
  '{Energia}', 'Médio', 20, '4d6 mental', 45, '3d20+10 (Percepção às Cegas)', '3d20+10', 20, '1d20+5', '3d20+10', '3d20+10', 100, 50, null, null,
  '{"agi":3,"for":null,"int":3,"pre":3,"vig":1}', null, 'Voo 12m | 8',
  '[{"nome":"Alterações Climáticas","descricao":"Altera o clima num raio de 90m ao redor (frio extremo, neblina, neve, vento forte)."},{"nome":"Vibrações Térmicas","descricao":"Invisível e incorpóreo, sons só como assovio de vento."},{"nome":"Imunidades","descricao":"Dano."}]',
  '[{"tipo":"Movimento","nome":"Granizo Perfurante","dano":"+2d8 perfuração (Reflexos DT 20 reduz à metade)","descricao":"Gera granizo; usando Congelar na mesma rodada, todos sem cobertura na área sofrem o dano; coberturas frágeis são destruídas."},{"tipo":"Padrão","nome":"Congelar","dano":"2d8 frio (Fortitude DT 20 reduz à metade)","descricao":"Raio 90m, todos sofrem o dano; afeta o cenário (nuvens escurecem, gelo cobre objetos = -1d20 em testes de manipular itens, gera granizo/chuva/vendaval); dura até o fim da cena ou missão."},{"tipo":"Padrão","nome":"Beijo Gélido","dano":"6d6 Energia + lenta (Fortitude DT 20 reduz à metade)","descricao":"Corpo a corpo, suga temperatura; reduzir a 0 PV (ou já estar em 0) transforma em \"estátua de gelo\" — petrificado até destruir a camada (20 PV, RD 20/fogo); não recupera PV mas não morre enquanto congelado; dano não-fogo na estátua também fere quem está dentro; Uivar recupera 20 PV ao petrificar; destruir a estátua tira 10 PV do Uivar, e se o congelado morrer, quem o matou sofre 6d6 dano mental (Vontade DT 20 reduz à metade)."}]',
  null, 72
),
(
  (select id from sources where slug = 'sobrevivendo_ao_horror'), 'Melancolia', 140,
  'Parasita invisível e incorpóreo que escala uma pessoa sem ser sentido, infectando-a com uma depressão paranormal progressiva. Cresce devagar como uma infecção, incapacitando a vítima até deformar seu rosto numa expressão permanente de tristeza exagerada. Sua presença é percebida por marcas na pele parecidas com tatuagens que se espalham quanto mais consome. Ao esgotar o hospedeiro, migra pra outro.',
  '{Conhecimento,Sangue,Morte}', 'Minúsculo (cresce)', 25, '4d8 mental', 50, '3d20+5 (Visão no Escuro)', '4d20+5', 29, '1d20+5', '4d20+5', '3d20+5', 200, 100, null, null,
  '{"agi":4,"for":null,"int":4,"pre":3,"vig":1}', 'Furtividade +4d20+5', '9m | 6',
  '[{"nome":"Parasita Invisível","descricao":"Invisível e incorpóreo; escala sem ser sentido; infectar exige a vítima passar em Vontade DT 25 no momento da tentativa (passando, nem percebe que foi alvo)."},{"nome":"Imunidades","descricao":"Dano."},{"nome":"Parasitose Melancólica","descricao":"Segue regras de doença (contaminação por contato, Vontade DT crescente por estágio). Estágio I (Medo, DT 25, parasita Minúsculo): fica abalado permanentemente (mesmo imune a medo). Estágio II (Sangue, DT 30, Pequeno): alquebrado e frustrado (mesmo imune a efeitos mentais). Estágio III (Morte, DT 35, Médio): esmorecido (mesmo imune a efeitos mentais). Estágio IV (Conhecimento, DT 40, Grande): todas as ações da vítima devem visar tirar a própria vida. Recuperar-se: 1 dia por estágio regredido (Estágio IV = 4 dias); curada, o parasita abandona e procura outra vítima. Parasitas Poderosos: já consumiu outros hospedeiros — DT do Estágio I equivale à dificuldade do tamanho do parasita (até Grande, DT 40)."}]',
  '[]',
  'A vítima precisa perceber o parasita primeiro (evento narrativo, ou falhar por 5 ou menos no teste de Vontade). Outros podem notar com Intuição/Medicina/Ocultismo/Profissão (psicólogo) na DT atual de resistência. Ajuda em forma de pequenos rituais (Ocultismo, mesma DT) reduz a DT de resistência em -5 por vez bem-sucedida. DT chegando a 0: Melancolia perde invisibilidade/incorporeidade/imunidade a dano, fica vulnerável a todo dano não-paranormal, e tenta fugir ou infectar outra vítima.', 73
),
(
  (select id from sources where slug = 'sobrevivendo_ao_horror'), 'Quibungo', 160,
  'Lenda do oeste africano que cresceu no folclore nordestino brasileiro, distorcida pelo Sangue. Criatura bestial peluda de mais de 3m, quatro braços, boca frontal com múltiplas mandíbulas para triturar, e uma bocarra enorme que se abre por todo o dorso pra engolir vítimas vivas — que podem levar dias sendo digeridas lentamente. Sem lógica por trás da crueldade; só devora.',
  '{Sangue}', 'Grande', 25, '4d8 mental', 55, '3d20+10 (Faro, Visão no Escuro)', '4d20+10', 34, '4d20+10', '4d20+10', '3d20+5', 320, 160, 'Balístico, impacto, perfuração e Sangue 20', 'Morte',
  '{"agi":4,"for":4,"int":1,"pre":3,"vig":4}', 'Atletismo +4d20+10, Furtividade +4d20+8, Sobrevivência +1d20+20', '15m | 10 · Escalada 15m | 10 · Natação 15m | 10',
  '[{"nome":"Besta da Mata","descricao":"Em mata fechada, +10 Furtividade e camuflagem total além de 9m."},{"nome":"Regeneração Acelerada","descricao":"Cura Acelerada 10/Morte."}]',
  '[{"tipo":"Padrão","nome":"Agredir (Garras, corpo a corpo x4)","teste":"4d20+20","dano":"2d6+10 corte"},{"tipo":"Padrão","nome":"Agredir (Mordida, corpo a corpo)","teste":"4d20+20","dano":"3d12+10 perfuração"},{"tipo":"Reação","nome":"Agarrão","teste":"4d20+22","descricao":"Ao acertar garras, tenta agarrar."},{"tipo":"Livre","nome":"Dilacerar","dano":"+1d12+10 perfuração","descricao":"1x/rodada, acertando 2 garras no mesmo alvo."},{"tipo":"Reação","nome":"Instintos Bestiais","descricao":"1x/rodada, esquiva completamente de ataque à distância ou efeito de área."},{"tipo":"Completa","nome":"Bocarra Torturadora","dano":"1d12+10 Sangue no início de cada turno do Quibungo","descricao":"Coloca um agarrado na bocarra dorsal — continua agarrado, tem cobertura mútua com o exterior; escapa vencendo teste de agarrar/Acrobacia ou causando 25+ dano ao Quibungo (aí fica caído adjacente); só mantém 1 por vez; se reduzido a 0 PV lá dentro, não morre nem fica inconsciente, só grita, até o Quibungo gastar ação completa pra engolir e matar (recupera 25 PV); outros podem libertar vencendo teste de agarrar (falhando, sofrem 1d12+10 perfuração); libertado com 0 PV fica inconsciente e morrendo normalmente; testemunhas de alguém mantido com 0 PV na bocarra sofrem 4d8 dano mental por turno (Vontade DT 25 reduz à metade)."},{"tipo":"Completa","nome":"Investida Brutal","descricao":"Percorre o dobro do deslocamento (mesmo não em linha reta) até o alvo; conta como investida (+1d20 ataques, -5 Defesa até o próximo turno); ao final, 2 ataques de garra."}]',
  null, 74
),
(
  (select id from sources where slug = 'sobrevivendo_ao_horror'), 'Profundo', 200,
  'Habita as profundezas oceânicas abissais — mergulhadores desaparecidos frequentemente o confundem com uma lula rara (Magnapinna) antes de perceber que são a presa. Pele esverdeada transparente/gelatinosa, corpo humanoide alongado de ~2m com "cabeça de lula" sem rosto, tentáculos finíssimos de até 8m. Sistema nervoso bioluminescente vermelho visível através da pele, que se intensifica antes de atacar, quando o corpo se abre revelando fileiras de dentes pontiagudos. Dilacera e dissolve vítimas rapidamente, deixando só uma mancha vermelha no abismo.',
  '{Energia,Sangue}', 'Enorme', 30, '6d6 mental', 65, '2d20+10 (Percepção às Cegas, Visão no Escuro)', '4d20+15', 34, '2d20+10', '4d20+15', '2d20+10', 380, 190, 'Balístico, corte, impacto, perfuração, Energia e Sangue 20', 'Conhecimento',
  '{"agi":4,"for":4,"int":2,"pre":2,"vig":2}', 'Furtividade +4d20+10', '6m | 4 · Natação 15m | 10',
  '[{"nome":"Camuflagem Submersa","descricao":"Submerso, camuflagem contra seres a 1,5m e total além disso, +10 Furtividade."},{"nome":"Regeneração Acelerada","descricao":"Cura Acelerada 20/Morte e fogo."}]',
  '[{"tipo":"Padrão","nome":"Agredir (Mordida, corpo a corpo)","teste":"4d20+25","dano":"4d10+20 perfuração"},{"tipo":"Padrão","nome":"Agredir (Tentáculos, corpo a corpo x6, máx. 2 no mesmo alvo por ação)","teste":"4d20+25","dano":"2d10+10 impacto"},{"tipo":"Reação","nome":"Agarrão","teste":"4d20+30","descricao":"Ao acertar tentáculo, tenta agarrar; só 1 agarrado por vez, mas não perde os ataques de tentáculo ao fazer isso."},{"tipo":"Livre","nome":"Mastigar","descricao":"1x/rodada, acertando 2 tentáculos no mesmo alvo na mesma rodada, +1 ataque de mordida."},{"tipo":"Completa","nome":"Engolir","teste":"4d20+30","dano":"2d10 Sangue + 2d10 perfuração no início de cada turno do Profundo","descricao":"Começando o turno agarrando alguém, testa agarrar pra engolir; engolido fica agarrado + cego + cobertura total mútua; escapa vencendo agarrar/Acrobacia ou causando 30+ dano (é regurgitado, cai adjacente); só 1 engolido por vez; ajuda externa exige ação de movimento + Percepção DT 25 pra achar o ponto certo."},{"tipo":"Completa","nome":"Onda Energética","descricao":"Raio 90m, enlouquece sistemas eletrônicos (desligam, piscam, curto, explodem — critério do mestre); item portado pode ser protegido com Vontade DT 25 do portador."}]',
  null, 75
),
(
  (select id from sources where slug = 'sobrevivendo_ao_horror'), 'Memento Mori', 260,
  'Presságio da morte, com raízes em lendas históricas humanas (associada aos médicos da peste do século XIV). Humanoide encapuzado com crânio de pássaro apodrecido no lugar do rosto, Lodo preto escorrendo dos olhos; manto que se mescla a penas negras; carrega a Ampulheta da Morte preenchida por cinzas. Move-se devagar mas é implacável: quem é escolhido nunca escapa de fato, só ganha tempo.',
  '{Morte,Conhecimento}', 'Médio', 35, '8d6 mental', 80, '3d20+20 (Visão no Escuro)', '1d20+15', 44, '3d20+20', '1d20+15', '3d20+20', 650, 325, 'Balístico, corte, impacto, perfuração e Morte 20', 'Energia',
  '{"agi":1,"for":1,"int":3,"pre":3,"vig":3}', 'Furtividade +1d20+30', '9m | 6',
  '[{"nome":"A Ampulheta da Morte","descricao":"Surge já vinculado a um alvo (normalmente pessoa), cujo tempo de vida é contado pela areia da ampulheta; nas mãos de alguém, conta como item amaldiçoado de Morte indestrutível, empunhado com 1 mão, 1 espaço; portador gasta ação padrão + 2 PE + 2 Sanidade pra descobrir o nome do vinculado e uma estimativa (não exata) do tempo restante."},{"nome":"Ininterrupto","descricao":"Só usa 1 ação por rodada pra se mover, mas nunca é afetado por condições/efeitos que reduzam ou impeçam deslocamento."},{"nome":"Inevitável Fim","descricao":"Reduzido a 0 PV, não morre: desaparece em cinzas/sombras até o fim da cena, podendo reaparecer depois pra continuar perseguindo."}]',
  '[{"tipo":"Padrão","nome":"Agredir (Garras, corpo a corpo x2)","teste":"5d20+30","dano":"4d10+30 corte"},{"tipo":"Movimento","nome":"Visagem","descricao":"Até 3x/cena, teletransporta pra espaço desocupado em alcance extremo; alternativamente, gasta um uso pra ficar invisível até fazer uma ação que não seja se mover."},{"tipo":"Padrão","nome":"Encarar o Abismo","dano":"4d10+30 Morte (Vontade DT 35 reduz o dano à metade e evita a revelação)","descricao":"Alvo em alcance curto sofre o dano e revela memórias/pensamentos; costuma usar pra localizar a ampulheta perdida."},{"tipo":"Padrão","nome":"Revelar a Ampulheta","dano":"8d6 mental (Vontade DT 35 reduz à metade)","descricao":"Todos em 36m que veem a ampulheta testemunham presságios de mortes."},{"tipo":"Completa","nome":"Atrair a Ampulheta","descricao":"Em alcance curto dela (mesmo sem ver), teletransporta a ampulheta pras próprias mãos."}]',
  'Sem a ampulheta, o Memento Mori para de perseguir o alvo e passa a perseguir o item até recuperá-lo. Existem mitos sobre um ritual capaz de destruir a ampulheta, matando o Memento Mori de vez e libertando o alvo — mas sem informações concretas sobre como (a critério do mestre).', 76
),
(
  (select id from sources where slug = 'sobrevivendo_ao_horror'), 'Rascunho', 300,
  'Manifestação de um horror esquecido — uma memória apagada que cresce como tumor mental, o vazio do esquecimento tomando forma. Contornos negros mutantes rasgando o ar. Não pode ser vista diretamente — só percebida pelo canto do olho, sombras que se movem, silhuetas nos cantos do quarto.',
  '{Conhecimento,Energia}', 'Médio', 35, '7d8 mental', 90, '5d20+25 (Percepção às Cegas, Visão no Escuro)', '2d20+15', 48, '5d20+20', '2d20+15', '5d20+25', 750, 375, 'Balístico, corte, impacto, perfuração, Conhecimento e Energia 20', 'Sangue',
  '{"agi":2,"for":2,"int":5,"pre":5,"vig":2}', null, '15m | 10',
  '[{"nome":"Ele Não Existe","descricao":"Invisível, inaudível e incorpóreo (sucesso automático em Furtividade) enquanto ninguém a observa diretamente (mesmo por reflexo); sendo observada, perde essas 3 características; combater sem olhar diretamente pra ela dá as mesmas penalidades de estar cego."},{"nome":"Vulnerabilidade à Luz","descricao":"Em ambiente totalmente iluminado, -10 Defesa, perde resistências a dano, tenta fugir."}]',
  '[{"tipo":"Movimento","nome":"Possuir Objeto","dano":"4d6 impacto (Reflexos DT 35 reduz à metade; dobra se o objeto for muito pesado)","descricao":"Não sendo observada, 1x/rodada, telecinesia arremessa objeto em alcance médio."},{"tipo":"Padrão","nome":"Aterrorizar","dano":"7d8 mental (Vontade DT 35 reduz à metade)","descricao":"Todos em 9m à escolha."},{"tipo":"Completa","nome":"Piscar","descricao":"Até 3x/cena, teletransporta pra espaço desocupado em alcance extremo (mesmo sem linha de visão); surgindo adjacente a alguém, pode usar Aterrorizar como ação livre nele."}]',
  null, 77
),
(
  (select id from sources where slug = 'sobrevivendo_ao_horror'), 'Medusa', 320,
  'Mito grego distorcido pelo Outro Lado — versão ainda mais cruel da górgona que petrifica com o olhar. Forma feminina serpentina, sombria, corpo esquelético perturbador, só os olhos penetrantes visíveis nas sombras. Territorial: mantém um covil/templo esculpido pelos corpos de vítimas que sucumbiram à tentação de contemplá-la — cada uma paralisada, eternamente acordada e fitando sua algoz.',
  '{Conhecimento,Morte}', 'Grande', 40, '9d6 mental', 95, '5d20+25 (Faro, Visão no Escuro)', '4d20+20', 50, '4d20+20', '4d20+20', '5d20+25', 380, 190, 'Corte, impacto, perfuração e Morte 20', 'Sangue',
  '{"agi":5,"for":5,"int":4,"pre":5,"vig":3}', null, '12m | 8 · Escalada 12m | 8 · Natação 12m | 8',
  '[{"nome":"Imunidades","descricao":"Conhecimento."},{"nome":"Camuflagem Sombria","descricao":"Em penumbra/escuridão, camuflagem + 10 Furtividade."},{"nome":"Conhecimento de Eras","descricao":"Expert em toda perícia não listada (+4d20+20); comunica-se normalmente."},{"nome":"Olhar Petrificante","descricao":"Quem olha nos olhos dela testa Reflexos DT 40 ou fica petrificado (paralisia temporal, não física — dano não revela passagem de tempo); só salva matando a Medusa; lutar sem olhar dá penalidades de cego."},{"nome":"Recuperação Acelerada","descricao":"Cura Acelerada 20, mas não recupera dano crítico ou corte no pescoço (Defesa 60 nesse alvo específico)."},{"nome":"Veneno Mortal","descricao":"Garra/jato venenoso envenena; Fortitude DT 40 no início de cada turno ou 4d10 dano de Morte (passar cura)."}]',
  '[{"tipo":"Padrão","nome":"Agredir (Garras, corpo a corpo x2)","teste":"5d20+35","dano":"8d8+20 corte"},{"tipo":"Padrão","nome":"Agredir (Cauda, distância curto)","teste":"5d20+35","dano":"8d8+40 impacto"},{"tipo":"Padrão","nome":"Agredir (Jato Venenoso, distância longo)","teste":"5d20+35","dano":"8d12 Morte"},{"tipo":"Reação","nome":"Agarrão","teste":"5d20+37","descricao":"Ao acertar cauda, tenta agarrar."},{"tipo":"Livre","nome":"Dilacerar","dano":"+8d8 corte","descricao":"Acertando as 2 garras."},{"tipo":"Padrão","nome":"Sussurrar Maléfico","dano":"6d10 mental (Vontade DT 40 reduz à metade)","descricao":"Alvo em alcance médio."},{"tipo":"Padrão","nome":"Sugestões Irresistíveis","descricao":"Alvo em alcance médio testa Vontade DT 40 ou não consegue evitar olhar pra ela até o início do próprio próximo turno."},{"tipo":"Completa","nome":"Rastejar Imparável","descricao":"Percorre o dobro do deslocamento ignorando terreno difícil; terminando adjacente a alguém, ataca com garras/cauda como ação livre."}]',
  null, 78
),
(
  (select id from sources where slug = 'sobrevivendo_ao_horror'), 'Amigo Imaginário', 360,
  'Obra de arte perfeita tomada forma — resultado do delírio coletivo de uma civilização isolada na ilha de Tipora, intensificado por um composto gerado por Sangue e Morte através do "Sino de Tenebris". Ser encapuzado de mais de 2,5m, alongado e curvado, tentáculos sob um manto marrom irreconhecível escondendo braços apodrecidos com dedos esqueléticos. Uma cascata de tinta vermelho-ocre jorra de onde deveria ser o rosto. Alimenta-se do medo de quem teve seus segredos manipulados. Originada no "Incidente da Ilha" — a manifestação original foi contida, mas o trauma dos sobreviventes segue alimentando sua força através de "quadros" ligados ao Medo.',
  '{Morte,Sangue}', 'Grande', 40, '8d8 mental (sem imunidade por NEX)', null, '5d20+30 (Percepção às Cegas, alcance extremo)', '5d20+30', 56, '4d20+20', '5d20+30', '5d20+30', 1000, 500, 'Balístico, corte, impacto e perfuração 20', 'Energia',
  '{"agi":5,"for":5,"int":3,"pre":5,"vig":4}', 'Furtividade +5d20+28 (+5d20+48 se em um quadro)', '12m | 8',
  '[{"nome":"Imunidades","descricao":"Morte, Sangue."},{"nome":"Quadros","descricao":"Existem 7 pinturas ligadas à criatura; observar uma delas por um tempo exige Vontade DT 40 — falhando, \"Entra no Quadro\": revive memórias/traumas/ilusões (a critério do mestre) e sofre 8d8 dano mental (passar evita o dano); cada vez que alguém entra num quadro, a Membrana na região se deteriora mais, \"alimentando\" o Medo local."},{"nome":"O Sino","descricao":"Ao aparecer, todos em alcance extremo capazes de ouvir ficam pasmos 1 rodada (Vontade DT 40 evita e imuniza até o fim da cena); quem falhou E \"Entrou num Quadro\" fica impedido de se afastar até o fim da cena; repete no início de cada turno da criatura."},{"nome":"Frenesi de Sangue (ao ficar machucado)","descricao":"Vigor vira 5, Fortitude vira 5d20+30, ganha escalada 15m/10, 2 ações padrão + 2 de movimento; O Sino passa a forçar a pessoa que falha a atacar/morder o ser vivo mais próximo (ou a si mesma) em vez de ficar pasma; quem já resistiu à versão anterior do Sino precisa testar de novo contra a nova versão."}]',
  '[{"tipo":"Padrão","nome":"Agredir (Garras, corpo a corpo x2)","teste":"5d20+40","dano":"4d10+10 corte"},{"tipo":"Padrão","nome":"Agredir (Tentáculos, distância médio)","teste":"5d20+40","dano":"4d10+20 impacto"},{"tipo":"Reação","nome":"Agarrão","teste":"5d20+42","descricao":"Ao acertar tentáculos, tenta agarrar; agarrado liberta-se destruindo o tentáculo (Defesa 30, PV 50, imune a Morte e Sangue, vulnerável a Energia); destruir um tentáculo tira 50 PV da criatura."},{"tipo":"Completa","nome":"Derreter","dano":"4d10+10 Morte + 4d10+10 Sangue (Fortitude DT 40 reduz à metade)","descricao":"Puxa agarrado até o rosto e despeja tinta corrosiva."},{"tipo":"Completa","nome":"Dissolver","dano":"4d10+20 químico (Fortitude DT 40 reduz à metade)","descricao":"Envolve agarrado com mais tentáculos tentando consumi-lo; recupera PV igual ao dano causado."}]',
  null, 79
);
