-- Bestiário Arquivos Secretos 07 — temas Vampyrus (predadores) e Terribilis Fides
-- (crenças esquecidas): Incinerado, Stryzga, Apóstata (VD dinâmico 80-320, 4 ritos).

insert into creatures (source_id, name, vd, flavor_text, descritores, tamanho, presenca_dt, presenca_dano, presenca_nex_imune, percepcao, iniciativa, defesa, fortitude, reflexos, vontade, pv_maximo, pv_machucado, resistencias, vulnerabilidades, atributos, pericias, deslocamento, habilidades, acoes, enigma_medo, sort_order)
values
(
  (select id from sources where slug = 'arquivos_secretos_07'), 'Incinerado', 60,
  'Vítima consumida pelo caos ígneo da Energia combinada com Sangue — corpo em chamas instáveis, prestes a explodir a qualquer momento. Ao reduzir alguém a Sanidade 0 ou 0 PV em chamas por perto, gera um novo incinerado.',
  '{Energia,Sangue}', 'Médio', 19, '3d6 mental', 35, '-2d20', '3d20+10', 21, '2d20+5', '3d20+10', '-2d20', 100, 50, 'Balístico, corte e perfuração 5, Sangue 10, Energia 20; imune a fogo', 'Balístico, fogo e Morte',
  '{"agi":3,"for":3,"int":0,"pre":0,"vig":2}', null, null,
  '[{"nome":"Combustão Caótica","descricao":"-10 PV no início do turno; machucado, ganha 2 ações padrão por rodada."},{"nome":"Consumido pelo Caos","descricao":"Ser com Sanidade 0 ou reduzido a 0 PV, em chamas, em alcance curto dele, vira um novo incinerado."},{"nome":"Natureza Incendiária","descricao":"Mira preferencialmente em alvos que possam pegar fogo/explodir."}]',
  '[{"tipo":"Padrão","nome":"Disparo de Labaredas, distância x2 curto","teste":"3d20+10","dano":"2d8+5 fogo + chamas"},{"tipo":"Reação","nome":"Alimentar as Chamas","descricao":"Cura metade do dano de \"em chamas\" de alguém perto dela."},{"tipo":"Reação","nome":"Instabilidade Ígnea","dano":"5d10 (metade mental/metade Energia) + chamas (Reflexos DT 19 reduz à metade)","descricao":"Ao chegar a 0 PV, explode num raio de 6m."},{"tipo":"Padrão","nome":"Agonia Incandescente","dano":"3d6 mental (Vontade DT 19; -5 no teste se já em chamas)","descricao":"18m."}]',
  null, 108
),
(
  (select id from sources where slug = 'arquivos_secretos_07'), 'Stryzga', 120,
  'Predadora de essência vital ligada a Sangue e Morte — lenda de vampirismo alado. Mata alguém e amaldiçoa: se não morrer queimada em 1d4+3 dias, uma nova stryzga nasce no túmulo mais próximo da vítima.',
  '{Sangue,Morte}', 'Médio', 23, '4d6 mental', 60, '4d20+10 (Visão no Escuro)', '3d20+10', 28, null, '3d20+10', '4d20+10', 240, 120, 'Balístico, impacto e perfuração 10, químico e Sangue 20', 'Balístico, fogo e Morte',
  '{"agi":3,"for":2,"int":3,"pre":4,"vig":null}', 'Acrobacia 3d20+10, Furtividade 3d20+20', '9m | 6, Escalada 12m | 8, Voo 12m | 8',
  '[{"nome":"Absorver Essência","descricao":"Alimentou-se 3x ou mais do mesmo alvo = +1d20 em testes contra ele."},{"nome":"Dois Corações","descricao":"Ao matar alguém, lança maldição: se a stryzga não morrer queimada em 1d4+3 dias, nova stryzga nasce no túmulo mais próximo da vítima."},{"nome":"Ecos de Essência","descricao":"+1d20 em testes contra seres relacionados a vítimas já consumidas."}]',
  '[{"tipo":"Padrão","nome":"Mordida e Garras, corpo a corpo x2","teste":"3d20+15","dano":"4d10+10 corte"},{"tipo":"Livre","nome":"Imitar Voz","dano":"4d6 mental (Vontade DT 23)","descricao":"Usando a voz de uma pessoa já consumida, num alvo em alcance curto emocionalmente afetável por ela."},{"tipo":"Reação","nome":"Alimentar-se","descricao":"Ao acertar mordida/garras."},{"tipo":"Reação","nome":"Constrição","teste":"3d20+15","dano":"4d10+10 corte (Fortitude DT 23 reduz à metade)","descricao":"Agarra e, 1x/rodada enquanto voa, causa o dano."},{"tipo":"Reação","nome":"Quebra-Ossos","dano":"+4d6 dano de queda","descricao":"Alternativa à Constrição: joga a vítima da altura."},{"tipo":"Reação","nome":"Rasante Silencioso","dano":"4d6 mental + apavorado → abalado (Vontade DT 23)","descricao":"Contra alvo desprevenido relacionado a uma vítima anterior."}]',
  null, 109
),
(
  (select id from sources where slug = 'arquivos_secretos_07'), 'Apóstata', 80,
  'Fanático de crenças esquecidas (Terribilis Fides), ligado a Conhecimento e Morte — escala dinamicamente através de 3 Ritos, ganhando poder conforme cultistas o veneram. VD base 80, podendo chegar a 320 na forma final. Nota: o texto-fonte não capturou o Enigma de Medo dela nesta extração (mencionado, mas o conteúdo estaria na página 73 do livro, não incluída aqui).',
  '{Conhecimento,Morte}', 'Médio', 20, '3d8 mental', 40, '3d20+10', '2d20', 23, '2d20+5', '2d20', '3d20+10', 111, 55, 'Balístico, corte e impacto 5, Morte 5, Conhecimento 20; imune a dano e todas as condições', 'Sangue',
  '{"agi":2,"for":2,"int":3,"pre":4,"vig":2}', null, '0m (Voo 12m | 8 só na forma VD 320)',
  '[{"nome":"Mentem Corrumpere","descricao":"Quem falha no teste vs. Presença Perturbadora não sofre dano mental — em vez disso é infectado (doença sem teste de resistência inicial; só teste diário de Vontade DT 20+1/dia pra resistir à compulsão de ficar a 90m dela). 4 estágios: I (crença falsa + treino em Religião); II (+5 Religião + alquebrado + desprevenido 1 rodada no início da cena); III (não pode atacá-la até ser atacado); IV (esmorecido + abalado permanente)."},{"nome":"Murus Idolorum","descricao":"Atravessar a parede dela causa 20d12 dano de Conhecimento (0 PV = deixa de existir, morre)."},{"nome":"Ritus — escala de VD (3 ritos)","descricao":"Primeiro Rito (Religião DT 25 estendido) → VD 160: DT 25/4d8 mental/NEX 55% imune, Defesa 34, PV 333/166, +10 em testes/dano/RD. Segundo Rito (DT 30) → VD 240: DT 31/6d8/NEX 75% imune, Defesa 42, PV 555/277, +15, +1 ataque de flagellum. Terceiro Rito (Vontade estendido, exige que metade dos participantes falhe) → VD 320: DT 40/9d6/NEX 95% imune, Defesa 50, PV 777/388, ganha Voo 12m|8, +20, +2 ataques de flagellum."}]',
  '[{"tipo":"Padrão","nome":"Flagellum, distância curto","teste":"3d20+10","dano":"6d10 mental"},{"tipo":"Reação","nome":"Idololatria (VD 160+)","descricao":"Cura metade do dano de flagellum causado."},{"tipo":"Reação","nome":"Gnosis Absoluta (VD 320+)","descricao":"Ao sofrer dano, +5 de RD permanente contra esse tipo de dano."},{"tipo":"Livre","nome":"Funes Ligantes","teste":"3d20+15","descricao":"Ao acertar flagellum, agarra (até 2 alvos simultâneos); os fios são atacáveis separadamente, PV 22 cada."},{"tipo":"Livre","nome":"Gnosis Implicata (VD 320+)","descricao":"Ao acertar flagellum, alvo fica vulnerável a dano mental até o fim da cena."},{"tipo":"Livre","nome":"Potentiam Absorbere","dano":"2d8 mental por agarrado + ataque extra de flagellum por agarrado","descricao":"."},{"tipo":"Movimento","nome":"Visio Vetita","dano":"6d8 mental (Vontade DT 35; crítico falho = cego permanente)","descricao":"18m."},{"tipo":"Completa","nome":"Vacuitatem Observa (VD 240+)","descricao":"Alcance médio, fascina; Vontade DT 30 (+5 se agarrado) ou a vítima gasta ações tentando atravessar um portal."}]',
  'Menção no livro, mas o texto não foi capturado nesta extração (estaria na página 73 do livro-fonte).', 110
);
